// Generated from the zeldaret/tww decomp's include/dolphin/gx/GXEnum.h. Do not edit.
// GX hardware register enums (BP/CP/XF register fields, FIFO commands, dirty flags) that the
// decomp's JSystem code uses and aurora's SDK does not declare. Names aurora defines as macros
// are skipped by #ifndef; names it declares as enumerators are left out entirely.
#ifndef SDK_COMPAT_PC_GX_HW_ENUMS_H
#define SDK_COMPAT_PC_GX_HW_ENUMS_H

#include <dolphin/gx.h>

#ifndef GX_COMPCNT_NULL
#define GX_COMPCNT_NULL ((GXCompCnt)(0))
#endif
#ifndef GX_COMP_NULL
#define GX_COMP_NULL ((GXCompType)(0))
#endif
#ifndef GX_TF_CI14
#define GX_TF_CI14 ((GXTexFmt)(0x9))
#endif
#ifndef GX_MAX_TLUT_ALL
#define GX_MAX_TLUT_ALL ((GXTlut)(GX_MAX_TLUT + GX_MAX_BIGTLUT))
#endif
#ifndef GX_CLAMP_BOTH
#define GX_CLAMP_BOTH ((GXFBClamp)(GX_CLAMP_TOP | GX_CLAMP_BOTTOM))
#endif
typedef enum _GXDirtyFlag {
    GX_DIRTY_SU_TEX = (1 << 0),
    GX_DIRTY_BP_MASK = (1 << 1),
    GX_DIRTY_GEN_MODE = (1 << 2),
    GX_DIRTY_VCD = (1 << 3),
    GX_DIRTY_VAT = (1 << 4),
    GX_DIRTY_AMB_COLOR0 = (1 << 8),
    GX_DIRTY_AMB_COLOR1 = (1 << 9),
    GX_DIRTY_MAT_COLOR0 = (1 << 10),
    GX_DIRTY_MAT_COLOR1 = (1 << 11),
    GX_DIRTY_MTX_IDX = (1 << 26),
    GX_DIRTY_PROJECTION = (1 << 27),
    GX_DIRTY_VIEWPORT = (1 << 28),
    GX_DIRTY_VLIM = GX_DIRTY_VCD | GX_DIRTY_VAT,
    GX_AMB_MAT_MASK =
        GX_DIRTY_AMB_COLOR0 | GX_DIRTY_AMB_COLOR1 | GX_DIRTY_MAT_COLOR0 | GX_DIRTY_MAT_COLOR1,
    GX_LIGHT_CHAN_MASK = 0x100F000,
    GX_TEX_GEN_MASK = 0x2FF0000,
} GXDirtyFlag;

typedef enum _GXCPVCDLo {
    GX_CP_VCD_LO_POSMTXIDX_ST = 31,
    GX_CP_VCD_LO_POSMTXIDX_END = 31,
    GX_CP_VCD_LO_TEX0MTXIDX_ST = 30,
    GX_CP_VCD_LO_TEX0MTXIDX_END = 30,
    GX_CP_VCD_LO_TEX1MTXIDX_ST = 29,
    GX_CP_VCD_LO_TEX1MTXIDX_END = 29,
    GX_CP_VCD_LO_TEX2MTXIDX_ST = 28,
    GX_CP_VCD_LO_TEX2MTXIDX_END = 28,
    GX_CP_VCD_LO_TEX3MTXIDX_ST = 27,
    GX_CP_VCD_LO_TEX3MTXIDX_END = 27,
    GX_CP_VCD_LO_TEX4MTXIDX_ST = 26,
    GX_CP_VCD_LO_TEX4MTXIDX_END = 26,
    GX_CP_VCD_LO_TEX5MTXIDX_ST = 25,
    GX_CP_VCD_LO_TEX5MTXIDX_END = 25,
    GX_CP_VCD_LO_TEX6MTXIDX_ST = 24,
    GX_CP_VCD_LO_TEX6MTXIDX_END = 24,
    GX_CP_VCD_LO_TEX7MTXIDX_ST = 23,
    GX_CP_VCD_LO_TEX7MTXIDX_END = 23,
    GX_CP_VCD_LO_POS_ST = 21,
    GX_CP_VCD_LO_POS_END = 22,
    GX_CP_VCD_LO_NRM_ST = 19,
    GX_CP_VCD_LO_NRM_END = 20,
    GX_CP_VCD_LO_CLRDIF_ST = 17,
    GX_CP_VCD_LO_CLRDIF_END = 18,
    GX_CP_VCD_LO_CLRSPEC_ST = 15,
    GX_CP_VCD_LO_CLRSPEC_END = 16,
} GXCPVCDLo;

typedef enum _GXCPVCDHi {
    GX_CP_VCD_HI_TEX0COORD_ST = 30,
    GX_CP_VCD_HI_TEX0COORD_END = 31,
    GX_CP_VCD_HI_TEX1COORD_ST = 28,
    GX_CP_VCD_HI_TEX1COORD_END = 29,
    GX_CP_VCD_HI_TEX2COORD_ST = 26,
    GX_CP_VCD_HI_TEX2COORD_END = 27,
    GX_CP_VCD_HI_TEX3COORD_ST = 24,
    GX_CP_VCD_HI_TEX3COORD_END = 25,
    GX_CP_VCD_HI_TEX4COORD_ST = 22,
    GX_CP_VCD_HI_TEX4COORD_END = 23,
    GX_CP_VCD_HI_TEX5COORD_ST = 20,
    GX_CP_VCD_HI_TEX5COORD_END = 21,
    GX_CP_VCD_HI_TEX6COORD_ST = 18,
    GX_CP_VCD_HI_TEX6COORD_END = 19,
    GX_CP_VCD_HI_TEX7COORD_ST = 16,
    GX_CP_VCD_HI_TEX7COORD_END = 17,
} GXCPVCDHi;

typedef enum _GXXFRegs {
#ifndef GX_XF_REG_ERROR
    GX_XF_REG_ERROR = 0x1000,
#endif
#ifndef GX_XF_REG_DIAGNOSTICS
    GX_XF_REG_DIAGNOSTICS = 0x1001,
#endif
#ifndef GX_XF_REG_STATE0
    GX_XF_REG_STATE0 = 0x1002,
#endif
#ifndef GX_XF_REG_STATE1
    GX_XF_REG_STATE1 = 0x1003,
#endif
#ifndef GX_XF_REG_CLOCK
    GX_XF_REG_CLOCK = 0x1004,
#endif
#ifndef GX_XF_REG_CLIPDISABLE
    GX_XF_REG_CLIPDISABLE = 0x1005,
#endif
#ifndef GX_XF_REG_PERF0
    GX_XF_REG_PERF0 = 0x1006,
#endif
#ifndef GX_XF_REG_PERF1
    GX_XF_REG_PERF1 = 0x1007,
#endif
#ifndef GX_XF_REG_INVERTEXSPEC
    GX_XF_REG_INVERTEXSPEC = 0x1008,
#endif
#ifndef GX_XF_REG_NUMCOLORS
    GX_XF_REG_NUMCOLORS = 0x1009,
#endif
#ifndef GX_XF_REG_AMBIENT0
    GX_XF_REG_AMBIENT0 = 0x100A,
#endif
#ifndef GX_XF_REG_AMBIENT1
    GX_XF_REG_AMBIENT1 = 0x100B,
#endif
#ifndef GX_XF_REG_MATERIAL0
    GX_XF_REG_MATERIAL0 = 0x100C,
#endif
#ifndef GX_XF_REG_MATERIAL1
    GX_XF_REG_MATERIAL1 = 0x100D,
#endif
#ifndef GX_XF_REG_COLOR0CNTRL
    GX_XF_REG_COLOR0CNTRL = 0x100E,
#endif
#ifndef GX_XF_REG_COLOR1CNTRL
    GX_XF_REG_COLOR1CNTRL = 0x100F,
#endif
#ifndef GX_XF_REG_ALPHA0CNTRL
    GX_XF_REG_ALPHA0CNTRL = 0x1010,
#endif
#ifndef GX_XF_REG_ALPHA1CNTRL
    GX_XF_REG_ALPHA1CNTRL = 0x1011,
#endif
#ifndef GX_XF_REG_DUALTEXTRAN
    GX_XF_REG_DUALTEXTRAN = 0x1012,
#endif
#ifndef GX_XF_REG_MATRIXINDEX0
    GX_XF_REG_MATRIXINDEX0 = 0x1018,
#endif
#ifndef GX_XF_REG_MATRIXINDEX1
    GX_XF_REG_MATRIXINDEX1 = 0x1019,
#endif
#ifndef GX_XF_REG_SCALEX
    GX_XF_REG_SCALEX = 0x101A,
#endif
#ifndef GX_XF_REG_SCALEY
    GX_XF_REG_SCALEY = 0x101B,
#endif
#ifndef GX_XF_REG_SCALEZ
    GX_XF_REG_SCALEZ = 0x101C,
#endif
#ifndef GX_XF_REG_OFFSETX
    GX_XF_REG_OFFSETX = 0x101D,
#endif
#ifndef GX_XF_REG_OFFSETY
    GX_XF_REG_OFFSETY = 0x101E,
#endif
#ifndef GX_XF_REG_OFFSETZ
    GX_XF_REG_OFFSETZ = 0x101F,
#endif
#ifndef GX_XF_REG_PROJECTIONA
    GX_XF_REG_PROJECTIONA = 0x1020,
#endif
#ifndef GX_XF_REG_PROJECTIONB
    GX_XF_REG_PROJECTIONB = 0x1021,
#endif
#ifndef GX_XF_REG_PROJECTIONC
    GX_XF_REG_PROJECTIONC = 0x1022,
#endif
#ifndef GX_XF_REG_PROJECTIOND
    GX_XF_REG_PROJECTIOND = 0x1023,
#endif
#ifndef GX_XF_REG_PROJECTIONE
    GX_XF_REG_PROJECTIONE = 0x1024,
#endif
#ifndef GX_XF_REG_PROJECTIONF
    GX_XF_REG_PROJECTIONF = 0x1025,
#endif
#ifndef GX_XF_REG_PROJECTORTHO
    GX_XF_REG_PROJECTORTHO = 0x1026,
#endif
#ifndef GX_XF_REG_NUMTEX
    GX_XF_REG_NUMTEX = 0x103F,
#endif
#ifndef GX_XF_REG_TEX0
    GX_XF_REG_TEX0 = 0x1040,
#endif
#ifndef GX_XF_REG_TEX1
    GX_XF_REG_TEX1 = 0x1041,
#endif
#ifndef GX_XF_REG_TEX2
    GX_XF_REG_TEX2 = 0x1042,
#endif
#ifndef GX_XF_REG_TEX3
    GX_XF_REG_TEX3 = 0x1043,
#endif
#ifndef GX_XF_REG_TEX4
    GX_XF_REG_TEX4 = 0x1044,
#endif
#ifndef GX_XF_REG_TEX5
    GX_XF_REG_TEX5 = 0x1045,
#endif
#ifndef GX_XF_REG_TEX6
    GX_XF_REG_TEX6 = 0x1046,
#endif
#ifndef GX_XF_REG_TEX7
    GX_XF_REG_TEX7 = 0x1047,
#endif
#ifndef GX_XF_REG_DUALTEX0
    GX_XF_REG_DUALTEX0 = 0x1050,
#endif
#ifndef GX_XF_REG_DUALTEX1
    GX_XF_REG_DUALTEX1 = 0x1051,
#endif
#ifndef GX_XF_REG_DUALTEX2
    GX_XF_REG_DUALTEX2 = 0x1052,
#endif
#ifndef GX_XF_REG_DUALTEX3
    GX_XF_REG_DUALTEX3 = 0x1053,
#endif
#ifndef GX_XF_REG_DUALTEX4
    GX_XF_REG_DUALTEX4 = 0x1054,
#endif
#ifndef GX_XF_REG_DUALTEX5
    GX_XF_REG_DUALTEX5 = 0x1055,
#endif
#ifndef GX_XF_REG_DUALTEX6
    GX_XF_REG_DUALTEX6 = 0x1056,
#endif
#ifndef GX_XF_REG_DUALTEX7
    GX_XF_REG_DUALTEX7 = 0x1057,
#endif
} GXXFRegs;

typedef enum _GXFifoCmd {
    GX_FIFO_CMD_NOOP = 0x00,
    GX_FIFO_CMD_LOAD_BP_REG = 0x61,
    GX_FIFO_CMD_LOAD_CP_REG = 0x08,
    GX_FIFO_CMD_LOAD_XF_REG = 0x10,
    GX_FIFO_CMD_LOAD_INDX_A = 0x20,
    GX_FIFO_CMD_LOAD_INDX_B = 0x28,
    GX_FIFO_CMD_LOAD_INDX_C = 0x30,
    GX_FIFO_CMD_LOAD_INDX_D = 0x38,
    GX_FIFO_CMD_CALL_DL = 0x40,
    GX_FIFO_CMD_INVAL_VTX = 0x48,
} GXFifoCmd;

typedef enum _GXCPVATGrp0 {
    GX_CP_VAT_GRP0_POS_CNT_ST = 31,
    GX_CP_VAT_GRP0_POS_CNT_END = 31,
    GX_CP_VAT_GRP0_POS_TYPE_ST = 28,
    GX_CP_VAT_GRP0_POS_TYPE_END = 30,
    GX_CP_VAT_GRP0_POS_SHIFT_ST = 23,
    GX_CP_VAT_GRP0_POS_SHIFT_END = 27,
    GX_CP_VAT_GRP0_NRM_CNT_ST = 22,
    GX_CP_VAT_GRP0_NRM_CNT_END = 22,
    GX_CP_VAT_GRP0_NRM_TYPE_ST = 19,
    GX_CP_VAT_GRP0_NRM_TYPE_END = 21,
    GX_CP_VAT_GRP0_CLRDIFF_CNT_ST = 18,
    GX_CP_VAT_GRP0_CLRDIFF_CNT_END = 18,
    GX_CP_VAT_GRP0_CLRDIFF_TYPE_ST = 15,
    GX_CP_VAT_GRP0_CLRDIFF_TYPE_END = 17,
    GX_CP_VAT_GRP0_CLRSPEC_CNT_ST = 14,
    GX_CP_VAT_GRP0_CLRSPEC_CNT_END = 14,
    GX_CP_VAT_GRP0_CLRSPEC_TYPE_ST = 11,
    GX_CP_VAT_GRP0_CLRSPEC_TYPE_END = 13,
    GX_CP_VAT_GRP0_TXC0_CNT_ST = 10,
    GX_CP_VAT_GRP0_TXC0_CNT_END = 10,
    GX_CP_VAT_GRP0_TXC0_TYPE_ST = 7,
    GX_CP_VAT_GRP0_TXC0_TYPE_END = 9,
    GX_CP_VAT_GRP0_TXC0_SHIFT_ST = 2,
    GX_CP_VAT_GRP0_TXC0_SHIFT_END = 6,
    GX_CP_VAT_GRP0_BYTEDEQ_ST = 1,
    GX_CP_VAT_GRP0_BYTEDEQ_END = 1,
    GX_CP_VAT_GRP0_NRMIDX3_ST = 0,
    GX_CP_VAT_GRP0_NRMIDX3_END = 0,
} GXCPVATGrp0;

typedef enum _GXCPVATGrp1 {
    GX_CP_VAT_GRP1_TXC1_CNT_ST = 31,
    GX_CP_VAT_GRP1_TXC1_CNT_END = 31,
    GX_CP_VAT_GRP1_TXC1_TYPE_ST = 28,
    GX_CP_VAT_GRP1_TXC1_TYPE_END = 30,
    GX_CP_VAT_GRP1_TXC1_SHIFT_ST = 23,
    GX_CP_VAT_GRP1_TXC1_SHIFT_END = 27,
    GX_CP_VAT_GRP1_TXC2_CNT_ST = 22,
    GX_CP_VAT_GRP1_TXC2_CNT_END = 22,
    GX_CP_VAT_GRP1_TXC2_TYPE_ST = 19,
    GX_CP_VAT_GRP1_TXC2_TYPE_END = 21,
    GX_CP_VAT_GRP1_TXC2_SHIFT_ST = 14,
    GX_CP_VAT_GRP1_TXC2_SHIFT_END = 18,
    GX_CP_VAT_GRP1_TXC3_CNT_ST = 13,
    GX_CP_VAT_GRP1_TXC3_CNT_END = 13,
    GX_CP_VAT_GRP1_TXC3_TYPE_ST = 10,
    GX_CP_VAT_GRP1_TXC3_TYPE_END = 12,
    GX_CP_VAT_GRP1_TXC3_SHIFT_ST = 5,
    GX_CP_VAT_GRP1_TXC3_SHIFT_END = 9,
    GX_CP_VAT_GRP1_TXC4_CNT_ST = 4,
    GX_CP_VAT_GRP1_TXC4_CNT_END = 4,
    GX_CP_VAT_GRP1_TXC4_TYPE_ST = 1,
    GX_CP_VAT_GRP1_TXC4_TYPE_END = 3,
} GXCPVATGrp1;

typedef enum _GXCPVATGrp2 {
    GX_CP_VAT_GRP2_TXC4_SHIFT_ST = 27,
    GX_CP_VAT_GRP2_TXC4_SHIFT_END = 31,
    GX_CP_VAT_GRP2_TXC5_CNT_ST = 26,
    GX_CP_VAT_GRP2_TXC5_CNT_END = 26,
    GX_CP_VAT_GRP2_TXC5_TYPE_ST = 23,
    GX_CP_VAT_GRP2_TXC5_TYPE_END = 25,
    GX_CP_VAT_GRP2_TXC5_SHIFT_ST = 18,
    GX_CP_VAT_GRP2_TXC5_SHIFT_END = 22,
    GX_CP_VAT_GRP2_TXC6_CNT_ST = 17,
    GX_CP_VAT_GRP2_TXC6_CNT_END = 17,
    GX_CP_VAT_GRP2_TXC6_TYPE_ST = 14,
    GX_CP_VAT_GRP2_TXC6_TYPE_END = 16,
    GX_CP_VAT_GRP2_TXC6_SHIFT_ST = 9,
    GX_CP_VAT_GRP2_TXC6_SHIFT_END = 13,
    GX_CP_VAT_GRP2_TXC7_CNT_ST = 8,
    GX_CP_VAT_GRP2_TXC7_CNT_END = 8,
    GX_CP_VAT_GRP2_TXC7_TYPE_ST = 5,
    GX_CP_VAT_GRP2_TXC7_TYPE_END = 7,
    GX_CP_VAT_GRP2_TXC7_SHIFT_ST = 0,
    GX_CP_VAT_GRP2_TXC7_SHIFT_END = 4,
} GXCPVATGrp2;

typedef enum _GXBPGenMode {
    GX_BP_GENMODE_NUMTEX_ST = 28,
    GX_BP_GENMODE_NUMTEX_END = 31,
    GX_BP_GENMODE_NUMCOLORS_ST = 25,
    GX_BP_GENMODE_NUMCOLORS_END = 27,
    GX_BP_GENMODE_MULTISAMPLE_ST = 22,
    GX_BP_GENMODE_MULTISAMPLE_END = 22,
    GX_BP_GENMODE_CULLMODE_ST = 16,
    GX_BP_GENMODE_CULLMODE_END = 17,
    GX_BP_GENMODE_NUMINDSTAGES_ST = 13,
    GX_BP_GENMODE_NUMINDSTAGES_END = 15,
    GX_BP_GENMODE_COPLANAR_ST = 12,
    GX_BP_GENMODE_COPLANAR_END = 12,
} GXBPGenMode;

typedef enum _GXXfTexReg {
    GX_XF_TEX_PROJ_ST = 0,
    GX_XF_TEX_PROJ_STQ = 1,
    GX_XF_TEX_FORM_AB11 = 0,
    GX_XF_TEX_FORM_ABC1 = 1,
} GXXfTexReg;

typedef enum _GXXFTex {
#ifndef GX_XF_TEX_PROJTYPE_ST
    GX_XF_TEX_PROJTYPE_ST = 30,
#endif
#ifndef GX_XF_TEX_PROJTYPE_END
    GX_XF_TEX_PROJTYPE_END = 30,
#endif
#ifndef GX_XF_TEX_INPUTFORM_ST
    GX_XF_TEX_INPUTFORM_ST = 29,
#endif
#ifndef GX_XF_TEX_INPUTFORM_END
    GX_XF_TEX_INPUTFORM_END = 29,
#endif
#ifndef GX_XF_TEX_TEXGENTYPE_ST
    GX_XF_TEX_TEXGENTYPE_ST = 25,
#endif
#ifndef GX_XF_TEX_TEXGENTYPE_END
    GX_XF_TEX_TEXGENTYPE_END = 27,
#endif
#ifndef GX_XF_TEX_SRCROW_ST
    GX_XF_TEX_SRCROW_ST = 20,
#endif
#ifndef GX_XF_TEX_SRCROW_END
    GX_XF_TEX_SRCROW_END = 24,
#endif
#ifndef GX_XF_TEX_BUMPSRCTEX_ST
    GX_XF_TEX_BUMPSRCTEX_ST = 17,
#endif
#ifndef GX_XF_TEX_BUMPSRCTEX_END
    GX_XF_TEX_BUMPSRCTEX_END = 19,
#endif
#ifndef GX_XF_TEX_BUMPSRCLIGHT_ST
    GX_XF_TEX_BUMPSRCLIGHT_ST = 14,
#endif
#ifndef GX_XF_TEX_BUMPSRCLIGHT_END
    GX_XF_TEX_BUMPSRCLIGHT_END = 16,
#endif
} GXXFTex;

typedef enum _GXXFDualTex {
    GX_XF_DUALTEX_BASEROW_ST = 26,
    GX_XF_DUALTEX_BASEROW_END = 31,
    GX_XF_DUALTEX_NORMALISE_ST = 23,
    GX_XF_DUALTEX_NORMALISE_END = 23,
} GXXFDualTex;

typedef enum _GXXfTexGen {
    GX_XF_TG_REGULAR = 0,
    GX_XF_TG_BUMP = 1,
    GX_XF_TG_CLR0 = 2,
    GX_XF_TG_CLR1 = 3,
} GXXfTexGen;

typedef enum _GXXFMtxIdx0 {
    GX_XF_MTXIDX0_GEOM_ST = 26,
    GX_XF_MTXIDX0_GEOM_END = 31,
    GX_XF_MTXIDX0_TEX0_ST = 20,
    GX_XF_MTXIDX0_TEX0_END = 25,
    GX_XF_MTXIDX0_TEX1_ST = 14,
    GX_XF_MTXIDX0_TEX1_END = 19,
    GX_XF_MTXIDX0_TEX2_ST = 8,
    GX_XF_MTXIDX0_TEX2_END = 13,
    GX_XF_MTXIDX0_TEX3_ST = 2,
    GX_XF_MTXIDX0_TEX3_END = 7,
} GXXFMtxIdx0;

typedef enum _GXXFMtxIdx1 {
    GX_XF_MTXIDX1_TEX4_ST = 26,
    GX_XF_MTXIDX1_TEX4_END = 31,
    GX_XF_MTXIDX1_TEX5_ST = 20,
    GX_XF_MTXIDX1_TEX5_END = 25,
    GX_XF_MTXIDX1_TEX6_ST = 14,
    GX_XF_MTXIDX1_TEX6_END = 19,
    GX_XF_MTXIDX1_TEX7_ST = 8,
    GX_XF_MTXIDX1_TEX7_END = 13,
} GXXFMtxIdx1;

typedef enum _GXBPRegs {
#ifndef GX_BP_REG_GENMODE
    GX_BP_REG_GENMODE = 0x0,
#endif
#ifndef GX_BP_REG_DISPCOPYFILTER0
    GX_BP_REG_DISPCOPYFILTER0 = 0x1,
#endif
#ifndef GX_BP_REG_DISPCOPYFILTER1
    GX_BP_REG_DISPCOPYFILTER1 = 0x2,
#endif
#ifndef GX_BP_REG_DISPCOPYFILTER2
    GX_BP_REG_DISPCOPYFILTER2 = 0x3,
#endif
#ifndef GX_BP_REG_DISPCOPYFILTER3
    GX_BP_REG_DISPCOPYFILTER3 = 0x4,
#endif
#ifndef GX_BP_REG_INDMTX0A
    GX_BP_REG_INDMTX0A = 0x6,
#endif
#ifndef GX_BP_REG_INDMTX0B
    GX_BP_REG_INDMTX0B = 0x7,
#endif
#ifndef GX_BP_REG_INDMTX0C
    GX_BP_REG_INDMTX0C = 0x8,
#endif
#ifndef GX_BP_REG_INDMTX1A
    GX_BP_REG_INDMTX1A = 0x9,
#endif
#ifndef GX_BP_REG_INDMTX1B
    GX_BP_REG_INDMTX1B = 0xA,
#endif
#ifndef GX_BP_REG_INDMTX1C
    GX_BP_REG_INDMTX1C = 0xB,
#endif
#ifndef GX_BP_REG_INDMTX2A
    GX_BP_REG_INDMTX2A = 0xC,
#endif
#ifndef GX_BP_REG_INDMTX2B
    GX_BP_REG_INDMTX2B = 0xD,
#endif
#ifndef GX_BP_REG_INDMTX2C
    GX_BP_REG_INDMTX2C = 0xE,
#endif
#ifndef GX_BP_REG_INDIMASK
    GX_BP_REG_INDIMASK = 0xF,
#endif
#ifndef GX_BP_REG_INDTEVSTAGE0
    GX_BP_REG_INDTEVSTAGE0 = 0x10,
#endif
#ifndef GX_BP_REG_INDTEVSTAGE1
    GX_BP_REG_INDTEVSTAGE1 = 0x11,
#endif
#ifndef GX_BP_REG_INDTEVSTAGE2
    GX_BP_REG_INDTEVSTAGE2 = 0x12,
#endif
#ifndef GX_BP_REG_INDTEVSTAGE3
    GX_BP_REG_INDTEVSTAGE3 = 0x13,
#endif
#ifndef GX_BP_REG_INDTEVSTAGE4
    GX_BP_REG_INDTEVSTAGE4 = 0x14,
#endif
#ifndef GX_BP_REG_INDTEVSTAGE5
    GX_BP_REG_INDTEVSTAGE5 = 0x15,
#endif
#ifndef GX_BP_REG_INDTEVSTAGE6
    GX_BP_REG_INDTEVSTAGE6 = 0x16,
#endif
#ifndef GX_BP_REG_INDTEVSTAGE7
    GX_BP_REG_INDTEVSTAGE7 = 0x17,
#endif
#ifndef GX_BP_REG_INDTEVSTAGE8
    GX_BP_REG_INDTEVSTAGE8 = 0x18,
#endif
#ifndef GX_BP_REG_INDTEVSTAGE9
    GX_BP_REG_INDTEVSTAGE9 = 0x19,
#endif
#ifndef GX_BP_REG_INDTEVSTAGE10
    GX_BP_REG_INDTEVSTAGE10 = 0x1A,
#endif
#ifndef GX_BP_REG_INDTEVSTAGE11
    GX_BP_REG_INDTEVSTAGE11 = 0x1B,
#endif
#ifndef GX_BP_REG_INDTEVSTAGE12
    GX_BP_REG_INDTEVSTAGE12 = 0x1C,
#endif
#ifndef GX_BP_REG_INDTEVSTAGE13
    GX_BP_REG_INDTEVSTAGE13 = 0x1D,
#endif
#ifndef GX_BP_REG_INDTEVSTAGE14
    GX_BP_REG_INDTEVSTAGE14 = 0x1E,
#endif
#ifndef GX_BP_REG_INDTEVSTAGE15
    GX_BP_REG_INDTEVSTAGE15 = 0x1F,
#endif
#ifndef GX_BP_REG_SCISSORTL
    GX_BP_REG_SCISSORTL = 0x20,
#endif
#ifndef GX_BP_REG_SCISSORBR
    GX_BP_REG_SCISSORBR = 0x21,
#endif
#ifndef GX_BP_REG_LINEPTWIDTH
    GX_BP_REG_LINEPTWIDTH = 0x22,
#endif
#ifndef GX_BP_REG_PERF0TRI
    GX_BP_REG_PERF0TRI = 0x23,
#endif
#ifndef GX_BP_REG_PERF0QUAD
    GX_BP_REG_PERF0QUAD = 0x24,
#endif
#ifndef GX_BP_REG_RAS1_SS0
    GX_BP_REG_RAS1_SS0 = 0x25,
#endif
#ifndef GX_BP_REG_RAS1_SS1
    GX_BP_REG_RAS1_SS1 = 0x26,
#endif
#ifndef GX_BP_REG_RAS1_IREF
    GX_BP_REG_RAS1_IREF = 0x27,
#endif
#ifndef GX_BP_REG_RAS1_TREF0
    GX_BP_REG_RAS1_TREF0 = 0x28,
#endif
#ifndef GX_BP_REG_RAS1_TREF1
    GX_BP_REG_RAS1_TREF1 = 0x29,
#endif
#ifndef GX_BP_REG_RAS1_TREF2
    GX_BP_REG_RAS1_TREF2 = 0x2A,
#endif
#ifndef GX_BP_REG_RAS1_TREF3
    GX_BP_REG_RAS1_TREF3 = 0x2B,
#endif
#ifndef GX_BP_REG_RAS1_TREF4
    GX_BP_REG_RAS1_TREF4 = 0x2C,
#endif
#ifndef GX_BP_REG_RAS1_TREF5
    GX_BP_REG_RAS1_TREF5 = 0x2D,
#endif
#ifndef GX_BP_REG_RAS1_TREF6
    GX_BP_REG_RAS1_TREF6 = 0x2E,
#endif
#ifndef GX_BP_REG_RAS1_TREF7
    GX_BP_REG_RAS1_TREF7 = 0x2F,
#endif
#ifndef GX_BP_REG_SU_SSIZE0
    GX_BP_REG_SU_SSIZE0 = 0x30,
#endif
#ifndef GX_BP_REG_SU_TSIZE0
    GX_BP_REG_SU_TSIZE0 = 0x31,
#endif
#ifndef GX_BP_REG_SU_SSIZE1
    GX_BP_REG_SU_SSIZE1 = 0x32,
#endif
#ifndef GX_BP_REG_SU_TSIZE1
    GX_BP_REG_SU_TSIZE1 = 0x33,
#endif
#ifndef GX_BP_REG_SU_SSIZE2
    GX_BP_REG_SU_SSIZE2 = 0x34,
#endif
#ifndef GX_BP_REG_SU_TSIZE2
    GX_BP_REG_SU_TSIZE2 = 0x35,
#endif
#ifndef GX_BP_REG_SU_SSIZE3
    GX_BP_REG_SU_SSIZE3 = 0x36,
#endif
#ifndef GX_BP_REG_SU_TSIZE3
    GX_BP_REG_SU_TSIZE3 = 0x37,
#endif
#ifndef GX_BP_REG_SU_SSIZE4
    GX_BP_REG_SU_SSIZE4 = 0x38,
#endif
#ifndef GX_BP_REG_SU_TSIZE4
    GX_BP_REG_SU_TSIZE4 = 0x39,
#endif
#ifndef GX_BP_REG_SU_SSIZE5
    GX_BP_REG_SU_SSIZE5 = 0x3A,
#endif
#ifndef GX_BP_REG_SU_TSIZE5
    GX_BP_REG_SU_TSIZE5 = 0x3B,
#endif
#ifndef GX_BP_REG_SU_SSIZE6
    GX_BP_REG_SU_SSIZE6 = 0x3C,
#endif
#ifndef GX_BP_REG_SU_TSIZE6
    GX_BP_REG_SU_TSIZE6 = 0x3D,
#endif
#ifndef GX_BP_REG_SU_SSIZE7
    GX_BP_REG_SU_SSIZE7 = 0x3E,
#endif
#ifndef GX_BP_REG_SU_TSIZE7
    GX_BP_REG_SU_TSIZE7 = 0x3F,
#endif
#ifndef GX_BP_REG_ZMODE
    GX_BP_REG_ZMODE = 0x40,
#endif
#ifndef GX_BP_REG_BLENDMODE
    GX_BP_REG_BLENDMODE = 0x41,
#endif
#ifndef GX_BP_REG_DSTALPHA
    GX_BP_REG_DSTALPHA = 0x42,
#endif
#ifndef GX_BP_REG_ZCONTROL
    GX_BP_REG_ZCONTROL = 0x43,
#endif
#ifndef GX_BP_REG_FIELDMASK
    GX_BP_REG_FIELDMASK = 0x44,
#endif
#ifndef GX_BP_REG_DRAWDONE
    GX_BP_REG_DRAWDONE = 0x45,
#endif
#ifndef GX_BP_REG_PETOKEN
    GX_BP_REG_PETOKEN = 0x47,
#endif
#ifndef GX_BP_REG_PETOKENINT
    GX_BP_REG_PETOKENINT = 0x48,
#endif
#ifndef GX_BP_REG_TEXCOPYSRCXY
    GX_BP_REG_TEXCOPYSRCXY = 0x49,
#endif
#ifndef GX_BP_REG_TEXCOPYSRCWH
    GX_BP_REG_TEXCOPYSRCWH = 0x4A,
#endif
#ifndef GX_BP_REG_TEXCOPYDST
    GX_BP_REG_TEXCOPYDST = 0x4B,
#endif
#ifndef GX_BP_REG_DISPCOPYSTRIDE
    GX_BP_REG_DISPCOPYSTRIDE = 0x4D,
#endif
#ifndef GX_BP_REG_DISPCOPYSCALEY
    GX_BP_REG_DISPCOPYSCALEY = 0x4E,
#endif
#ifndef GX_BP_REG_COPYCLEARAR
    GX_BP_REG_COPYCLEARAR = 0x4F,
#endif
#ifndef GX_BP_REG_COPYCLEARGB
    GX_BP_REG_COPYCLEARGB = 0x50,
#endif
#ifndef GX_BP_REG_COPYCLEARZ
    GX_BP_REG_COPYCLEARZ = 0x51,
#endif
#ifndef GX_BP_REG_COPYFILTER0
    GX_BP_REG_COPYFILTER0 = 0x53,
#endif
#ifndef GX_BP_REG_COPYFILTER1
    GX_BP_REG_COPYFILTER1 = 0x54,
#endif
#ifndef GX_BP_REG_BOUNDINGBOX0
    GX_BP_REG_BOUNDINGBOX0 = 0x55,
#endif
#ifndef GX_BP_REG_BOUNDINGBOX1
    GX_BP_REG_BOUNDINGBOX1 = 0x56,
#endif
#ifndef GX_BP_REG_SCISSOROFFSET
    GX_BP_REG_SCISSOROFFSET = 0x59,
#endif
#ifndef GX_BP_REG_TMEMPRELOADADDR
    GX_BP_REG_TMEMPRELOADADDR = 0x60,
#endif
#ifndef GX_BP_REG_TMEMPRELOADEVEN
    GX_BP_REG_TMEMPRELOADEVEN = 0x61,
#endif
#ifndef GX_BP_REG_TMEMPRELOADODD
    GX_BP_REG_TMEMPRELOADODD = 0x62,
#endif
#ifndef GX_BP_REG_TMEMPRELOADMODE
    GX_BP_REG_TMEMPRELOADMODE = 0x63,
#endif
#ifndef GX_BP_REG_TMEMTLUTSRC
    GX_BP_REG_TMEMTLUTSRC = 0x64,
#endif
#ifndef GX_BP_REG_TMEMTLUTDST
    GX_BP_REG_TMEMTLUTDST = 0x65,
#endif
#ifndef GX_BP_REG_TMEMTEXINVALIDATE
    GX_BP_REG_TMEMTEXINVALIDATE = 0x66,
#endif
#ifndef GX_BP_REG_PERF1
    GX_BP_REG_PERF1 = 0x67,
#endif
#ifndef GX_BP_REG_FIELDMODE
    GX_BP_REG_FIELDMODE = 0x68,
#endif
#ifndef GX_BP_REG_SETMODE0_TEX0
    GX_BP_REG_SETMODE0_TEX0 = 0x80,
#endif
#ifndef GX_BP_REG_SETMODE0_TEX1
    GX_BP_REG_SETMODE0_TEX1 = 0x81,
#endif
#ifndef GX_BP_REG_SETMODE0_TEX2
    GX_BP_REG_SETMODE0_TEX2 = 0x82,
#endif
#ifndef GX_BP_REG_SETMODE0_TEX3
    GX_BP_REG_SETMODE0_TEX3 = 0x83,
#endif
#ifndef GX_BP_REG_SETMODE1_TEX0
    GX_BP_REG_SETMODE1_TEX0 = 0x84,
#endif
#ifndef GX_BP_REG_SETMODE1_TEX1
    GX_BP_REG_SETMODE1_TEX1 = 0x85,
#endif
#ifndef GX_BP_REG_SETMODE1_TEX2
    GX_BP_REG_SETMODE1_TEX2 = 0x86,
#endif
#ifndef GX_BP_REG_SETMODE1_TEX3
    GX_BP_REG_SETMODE1_TEX3 = 0x87,
#endif
#ifndef GX_BP_REG_SETIMAGE0_TEX0
    GX_BP_REG_SETIMAGE0_TEX0 = 0x88,
#endif
#ifndef GX_BP_REG_SETIMAGE0_TEX1
    GX_BP_REG_SETIMAGE0_TEX1 = 0x89,
#endif
#ifndef GX_BP_REG_SETIMAGE0_TEX2
    GX_BP_REG_SETIMAGE0_TEX2 = 0x8A,
#endif
#ifndef GX_BP_REG_SETIMAGE0_TEX3
    GX_BP_REG_SETIMAGE0_TEX3 = 0x8B,
#endif
#ifndef GX_BP_REG_SETIMAGE1_TEX0
    GX_BP_REG_SETIMAGE1_TEX0 = 0x8C,
#endif
#ifndef GX_BP_REG_SETIMAGE1_TEX1
    GX_BP_REG_SETIMAGE1_TEX1 = 0x8D,
#endif
#ifndef GX_BP_REG_SETIMAGE1_TEX2
    GX_BP_REG_SETIMAGE1_TEX2 = 0x8E,
#endif
#ifndef GX_BP_REG_SETIMAGE1_TEX3
    GX_BP_REG_SETIMAGE1_TEX3 = 0x8F,
#endif
#ifndef GX_BP_REG_SETIMAGE2_TEX0
    GX_BP_REG_SETIMAGE2_TEX0 = 0x90,
#endif
#ifndef GX_BP_REG_SETIMAGE2_TEX1
    GX_BP_REG_SETIMAGE2_TEX1 = 0x91,
#endif
#ifndef GX_BP_REG_SETIMAGE2_TEX2
    GX_BP_REG_SETIMAGE2_TEX2 = 0x92,
#endif
#ifndef GX_BP_REG_SETIMAGE2_TEX3
    GX_BP_REG_SETIMAGE2_TEX3 = 0x93,
#endif
#ifndef GX_BP_REG_SETIMAGE3_TEX0
    GX_BP_REG_SETIMAGE3_TEX0 = 0x94,
#endif
#ifndef GX_BP_REG_SETIMAGE3_TEX1
    GX_BP_REG_SETIMAGE3_TEX1 = 0x95,
#endif
#ifndef GX_BP_REG_SETIMAGE3_TEX2
    GX_BP_REG_SETIMAGE3_TEX2 = 0x96,
#endif
#ifndef GX_BP_REG_SETIMAGE3_TEX3
    GX_BP_REG_SETIMAGE3_TEX3 = 0x97,
#endif
#ifndef GX_BP_REG_SETTLUT_TEX0
    GX_BP_REG_SETTLUT_TEX0 = 0x98,
#endif
#ifndef GX_BP_REG_SETTLUT_TEX1
    GX_BP_REG_SETTLUT_TEX1 = 0x99,
#endif
#ifndef GX_BP_REG_SETTLUT_TEX2
    GX_BP_REG_SETTLUT_TEX2 = 0x9A,
#endif
#ifndef GX_BP_REG_SETTLUT_TEX3
    GX_BP_REG_SETTLUT_TEX3 = 0x9B,
#endif
#ifndef GX_BP_REG_SETMODE0_TEX4
    GX_BP_REG_SETMODE0_TEX4 = 0xA0,
#endif
#ifndef GX_BP_REG_SETMODE0_TEX5
    GX_BP_REG_SETMODE0_TEX5 = 0xA1,
#endif
#ifndef GX_BP_REG_SETMODE0_TEX6
    GX_BP_REG_SETMODE0_TEX6 = 0xA2,
#endif
#ifndef GX_BP_REG_SETMODE0_TEX7
    GX_BP_REG_SETMODE0_TEX7 = 0xA3,
#endif
#ifndef GX_BP_REG_SETMODE1_TEX4
    GX_BP_REG_SETMODE1_TEX4 = 0xA4,
#endif
#ifndef GX_BP_REG_SETMODE1_TEX5
    GX_BP_REG_SETMODE1_TEX5 = 0xA5,
#endif
#ifndef GX_BP_REG_SETMODE1_TEX6
    GX_BP_REG_SETMODE1_TEX6 = 0xA6,
#endif
#ifndef GX_BP_REG_SETMODE1_TEX7
    GX_BP_REG_SETMODE1_TEX7 = 0xA7,
#endif
#ifndef GX_BP_REG_SETIMAGE0_TEX4
    GX_BP_REG_SETIMAGE0_TEX4 = 0xA8,
#endif
#ifndef GX_BP_REG_SETIMAGE0_TEX5
    GX_BP_REG_SETIMAGE0_TEX5 = 0xA9,
#endif
#ifndef GX_BP_REG_SETIMAGE0_TEX6
    GX_BP_REG_SETIMAGE0_TEX6 = 0xAA,
#endif
#ifndef GX_BP_REG_SETIMAGE0_TEX7
    GX_BP_REG_SETIMAGE0_TEX7 = 0xAB,
#endif
#ifndef GX_BP_REG_SETIMAGE1_TEX4
    GX_BP_REG_SETIMAGE1_TEX4 = 0xAC,
#endif
#ifndef GX_BP_REG_SETIMAGE1_TEX5
    GX_BP_REG_SETIMAGE1_TEX5 = 0xAD,
#endif
#ifndef GX_BP_REG_SETIMAGE1_TEX6
    GX_BP_REG_SETIMAGE1_TEX6 = 0xAE,
#endif
#ifndef GX_BP_REG_SETIMAGE1_TEX7
    GX_BP_REG_SETIMAGE1_TEX7 = 0xAF,
#endif
#ifndef GX_BP_REG_SETIMAGE2_TEX4
    GX_BP_REG_SETIMAGE2_TEX4 = 0xB0,
#endif
#ifndef GX_BP_REG_SETIMAGE2_TEX5
    GX_BP_REG_SETIMAGE2_TEX5 = 0xB1,
#endif
#ifndef GX_BP_REG_SETIMAGE2_TEX6
    GX_BP_REG_SETIMAGE2_TEX6 = 0xB2,
#endif
#ifndef GX_BP_REG_SETIMAGE2_TEX7
    GX_BP_REG_SETIMAGE2_TEX7 = 0xB3,
#endif
#ifndef GX_BP_REG_SETIMAGE3_TEX4
    GX_BP_REG_SETIMAGE3_TEX4 = 0xB4,
#endif
#ifndef GX_BP_REG_SETIMAGE3_TEX5
    GX_BP_REG_SETIMAGE3_TEX5 = 0xB5,
#endif
#ifndef GX_BP_REG_SETIMAGE3_TEX6
    GX_BP_REG_SETIMAGE3_TEX6 = 0xB6,
#endif
#ifndef GX_BP_REG_SETIMAGE3_TEX7
    GX_BP_REG_SETIMAGE3_TEX7 = 0xB7,
#endif
#ifndef GX_BP_REG_SETTLUT_TEX4
    GX_BP_REG_SETTLUT_TEX4 = 0xB8,
#endif
#ifndef GX_BP_REG_SETTLUT_TEX5
    GX_BP_REG_SETTLUT_TEX5 = 0xB9,
#endif
#ifndef GX_BP_REG_SETTLUT_TEX6
    GX_BP_REG_SETTLUT_TEX6 = 0xBA,
#endif
#ifndef GX_BP_REG_SETTLUT_TEX7
    GX_BP_REG_SETTLUT_TEX7 = 0xBB,
#endif
#ifndef GX_BP_REG_TEVCOLORCOMBINER0
    GX_BP_REG_TEVCOLORCOMBINER0 = 0xC0,
#endif
#ifndef GX_BP_REG_TEVALPHACOMBINER0
    GX_BP_REG_TEVALPHACOMBINER0 = 0xC1,
#endif
#ifndef GX_BP_REG_TEVCOLORCOMBINER1
    GX_BP_REG_TEVCOLORCOMBINER1 = 0xC2,
#endif
#ifndef GX_BP_REG_TEVALPHACOMBINER1
    GX_BP_REG_TEVALPHACOMBINER1 = 0xC3,
#endif
#ifndef GX_BP_REG_TEVCOLORCOMBINER2
    GX_BP_REG_TEVCOLORCOMBINER2 = 0xC4,
#endif
#ifndef GX_BP_REG_TEVALPHACOMBINER2
    GX_BP_REG_TEVALPHACOMBINER2 = 0xC5,
#endif
#ifndef GX_BP_REG_TEVCOLORCOMBINER3
    GX_BP_REG_TEVCOLORCOMBINER3 = 0xC6,
#endif
#ifndef GX_BP_REG_TEVALPHACOMBINER3
    GX_BP_REG_TEVALPHACOMBINER3 = 0xC7,
#endif
#ifndef GX_BP_REG_TEVCOLORCOMBINER4
    GX_BP_REG_TEVCOLORCOMBINER4 = 0xC8,
#endif
#ifndef GX_BP_REG_TEVALPHACOMBINER4
    GX_BP_REG_TEVALPHACOMBINER4 = 0xC9,
#endif
#ifndef GX_BP_REG_TEVCOLORCOMBINER5
    GX_BP_REG_TEVCOLORCOMBINER5 = 0xCA,
#endif
#ifndef GX_BP_REG_TEVALPHACOMBINER5
    GX_BP_REG_TEVALPHACOMBINER5 = 0xCB,
#endif
#ifndef GX_BP_REG_TEVCOLORCOMBINER6
    GX_BP_REG_TEVCOLORCOMBINER6 = 0xCC,
#endif
#ifndef GX_BP_REG_TEVALPHACOMBINER6
    GX_BP_REG_TEVALPHACOMBINER6 = 0xCD,
#endif
#ifndef GX_BP_REG_TEVCOLORCOMBINER7
    GX_BP_REG_TEVCOLORCOMBINER7 = 0xCE,
#endif
#ifndef GX_BP_REG_TEVALPHACOMBINER7
    GX_BP_REG_TEVALPHACOMBINER7 = 0xCF,
#endif
#ifndef GX_BP_REG_TEVCOLORCOMBINER8
    GX_BP_REG_TEVCOLORCOMBINER8 = 0xD0,
#endif
#ifndef GX_BP_REG_TEVALPHACOMBINER8
    GX_BP_REG_TEVALPHACOMBINER8 = 0xD1,
#endif
#ifndef GX_BP_REG_TEVCOLORCOMBINER9
    GX_BP_REG_TEVCOLORCOMBINER9 = 0xD2,
#endif
#ifndef GX_BP_REG_TEVALPHACOMBINER9
    GX_BP_REG_TEVALPHACOMBINER9 = 0xD3,
#endif
#ifndef GX_BP_REG_TEVCOLORCOMBINER10
    GX_BP_REG_TEVCOLORCOMBINER10 = 0xD4,
#endif
#ifndef GX_BP_REG_TEVALPHACOMBINER10
    GX_BP_REG_TEVALPHACOMBINER10 = 0xD5,
#endif
#ifndef GX_BP_REG_TEVCOLORCOMBINER11
    GX_BP_REG_TEVCOLORCOMBINER11 = 0xD6,
#endif
#ifndef GX_BP_REG_TEVALPHACOMBINER11
    GX_BP_REG_TEVALPHACOMBINER11 = 0xD7,
#endif
#ifndef GX_BP_REG_TEVCOLORCOMBINER12
    GX_BP_REG_TEVCOLORCOMBINER12 = 0xD8,
#endif
#ifndef GX_BP_REG_TEVALPHACOMBINER12
    GX_BP_REG_TEVALPHACOMBINER12 = 0xD9,
#endif
#ifndef GX_BP_REG_TEVCOLORCOMBINER13
    GX_BP_REG_TEVCOLORCOMBINER13 = 0xDA,
#endif
#ifndef GX_BP_REG_TEVALPHACOMBINER13
    GX_BP_REG_TEVALPHACOMBINER13 = 0xDB,
#endif
#ifndef GX_BP_REG_TEVCOLORCOMBINER14
    GX_BP_REG_TEVCOLORCOMBINER14 = 0xDC,
#endif
#ifndef GX_BP_REG_TEVALPHACOMBINER14
    GX_BP_REG_TEVALPHACOMBINER14 = 0xDD,
#endif
#ifndef GX_BP_REG_TEVCOLORCOMBINER15
    GX_BP_REG_TEVCOLORCOMBINER15 = 0xDE,
#endif
#ifndef GX_BP_REG_TEVALPHACOMBINER15
    GX_BP_REG_TEVALPHACOMBINER15 = 0xDF,
#endif
#ifndef GX_BP_REG_TEVREG0LO
    GX_BP_REG_TEVREG0LO = 0xE0,
#endif
#ifndef GX_BP_REG_TEVREG0HI
    GX_BP_REG_TEVREG0HI = 0xE1,
#endif
#ifndef GX_BP_REG_TEVREG1LO
    GX_BP_REG_TEVREG1LO = 0xE2,
#endif
#ifndef GX_BP_REG_TEVREG1HI
    GX_BP_REG_TEVREG1HI = 0xE3,
#endif
#ifndef GX_BP_REG_TEVREG2LO
    GX_BP_REG_TEVREG2LO = 0xE4,
#endif
#ifndef GX_BP_REG_TEVREG2HI
    GX_BP_REG_TEVREG2HI = 0xE5,
#endif
#ifndef GX_BP_REG_TEVREG3LO
    GX_BP_REG_TEVREG3LO = 0xE6,
#endif
#ifndef GX_BP_REG_TEVREG3HI
    GX_BP_REG_TEVREG3HI = 0xE7,
#endif
#ifndef GX_BP_REG_FOGRANGE
    GX_BP_REG_FOGRANGE = 0xE8,
#endif
#ifndef GX_BP_REG_FOGRANGEK0
    GX_BP_REG_FOGRANGEK0 = 0xE9,
#endif
#ifndef GX_BP_REG_FOGRANGEK1
    GX_BP_REG_FOGRANGEK1 = 0xEA,
#endif
#ifndef GX_BP_REG_FOGRANGEK2
    GX_BP_REG_FOGRANGEK2 = 0xEB,
#endif
#ifndef GX_BP_REG_FOGRANGEK3
    GX_BP_REG_FOGRANGEK3 = 0xEC,
#endif
#ifndef GX_BP_REG_FOGRANGEK4
    GX_BP_REG_FOGRANGEK4 = 0xED,
#endif
#ifndef GX_BP_REG_FOGPARAM0
    GX_BP_REG_FOGPARAM0 = 0xEE,
#endif
#ifndef GX_BP_REG_FOGPARAM1
    GX_BP_REG_FOGPARAM1 = 0xEF,
#endif
#ifndef GX_BP_REG_FOGPARAM2
    GX_BP_REG_FOGPARAM2 = 0xF0,
#endif
#ifndef GX_BP_REG_FOGPARAM3
    GX_BP_REG_FOGPARAM3 = 0xF1,
#endif
#ifndef GX_BP_REG_FOGCOLOR
    GX_BP_REG_FOGCOLOR = 0xF2,
#endif
#ifndef GX_BP_REG_ALPHACOMPARE
    GX_BP_REG_ALPHACOMPARE = 0xF3,
#endif
#ifndef GX_BP_REG_ZTEXTURE0
    GX_BP_REG_ZTEXTURE0 = 0xF4,
#endif
#ifndef GX_BP_REG_ZTEXTURE1
    GX_BP_REG_ZTEXTURE1 = 0xF5,
#endif
#ifndef GX_BP_REG_TEVKSEL0
    GX_BP_REG_TEVKSEL0 = 0xF6,
#endif
#ifndef GX_BP_REG_TEVKSEL1
    GX_BP_REG_TEVKSEL1 = 0xF7,
#endif
#ifndef GX_BP_REG_TEVKSEL2
    GX_BP_REG_TEVKSEL2 = 0xF8,
#endif
#ifndef GX_BP_REG_TEVKSEL3
    GX_BP_REG_TEVKSEL3 = 0xF9,
#endif
#ifndef GX_BP_REG_TEVKSEL4
    GX_BP_REG_TEVKSEL4 = 0xFA,
#endif
#ifndef GX_BP_REG_TEVKSEL5
    GX_BP_REG_TEVKSEL5 = 0xFB,
#endif
#ifndef GX_BP_REG_TEVKSEL6
    GX_BP_REG_TEVKSEL6 = 0xFC,
#endif
#ifndef GX_BP_REG_TEVKSEL7
    GX_BP_REG_TEVKSEL7 = 0xFD,
#endif
#ifndef GX_BP_REG_SSMASK
    GX_BP_REG_SSMASK = 0xFE,
#endif
} GXBPRegs;

typedef enum _GXBPFogParam0 {
    GX_BP_FOGPARAM0_A_MANT_ST = 21,
    GX_BP_FOGPARAM0_A_MANT_END = 31,
    GX_BP_FOGPARAM0_A_EXP_ST = 13,
    GX_BP_FOGPARAM0_A_EXP_END = 20,
    GX_BP_FOGPARAM0_A_SIGN_ST = 12,
    GX_BP_FOGPARAM0_A_SIGN_END = 12,
} GXBPFogParam0;

typedef enum _GXBPFogParam1 {
    GX_BP_FOGPARAM1_B_MAG_ST = 8,
    GX_BP_FOGPARAM1_B_MAG_END = 31,
} GXBPFogParam1;

typedef enum _GXBPFogParam2 {
    GX_BP_FOGPARAM2_B_SHIFT_ST = 27,
    GX_BP_FOGPARAM2_B_SHIFT_END = 31,
} GXBPFogParam2;

typedef enum _GXBPFogParam3 {
    GX_BP_FOGPARAM3_C_MANT_ST = 21,
    GX_BP_FOGPARAM3_C_MANT_END = 31,
    GX_BP_FOGPARAM3_C_EXP_ST = 13,
    GX_BP_FOGPARAM3_C_EXP_END = 20,
    GX_BP_FOGPARAM3_C_SIGN_ST = 12,
    GX_BP_FOGPARAM3_C_SIGN_END = 12,
    GX_BP_FOGPARAM3_PROJ_ST = 11,
    GX_BP_FOGPARAM3_PROJ_END = 11,
    GX_BP_FOGPARAM3_FSEL_ST = 8,
    GX_BP_FOGPARAM3_FSEL_END = 10,
} GXBPFogParam3;

typedef enum _GXBPFogColor {
    GX_BP_FOGCOLOR_RGB_ST = 8,
    GX_BP_FOGCOLOR_RGB_END = 31,
} GXBPFogColor;

typedef enum _GXBPFogRange {
    GX_BP_FOGRANGE_CENTER_ST = 22,
    GX_BP_FOGRANGE_CENTER_END = 31,
    GX_BP_FOGRANGE_ENABLED_ST = 21,
    GX_BP_FOGRANGE_ENABLED_END = 21,
} GXBPFogRange;

typedef enum _GXBPFogRangeK {
    GX_BP_FOGRANGEK_HI_ST = 20,
    GX_BP_FOGRANGEK_HI_END = 31,
    GX_BP_FOGRANGEK_LO_ST = 8,
    GX_BP_FOGRANGEK_LO_END = 19,
} GXBPFogRangeK;

typedef enum _GXBPBlendMode {
    GX_BP_BLENDMODE_ENABLE_ST = 31,
    GX_BP_BLENDMODE_ENABLE_END = 31,
    GX_BP_BLENDMODE_LOGIC_OP_ST = 30,
    GX_BP_BLENDMODE_LOGIC_OP_END = 30,
    GX_BP_BLENDMODE_DITHER_ST = 29,
    GX_BP_BLENDMODE_DITHER_END = 29,
    GX_BP_BLENDMODE_COLOR_UPDATE_ST = 28,
    GX_BP_BLENDMODE_COLOR_UPDATE_END = 28,
    GX_BP_BLENDMODE_ALPHA_UPDATE_ST = 27,
    GX_BP_BLENDMODE_ALPHA_UPDATE_END = 27,
    GX_BP_BLENDMODE_DSTFACTOR_ST = 24,
    GX_BP_BLENDMODE_DSTFACTOR_END = 26,
    GX_BP_BLENDMODE_SRCFACTOR_ST = 21,
    GX_BP_BLENDMODE_SRCFACTOR_END = 23,
    GX_BP_BLENDMODE_SUBTRACT_ST = 20,
    GX_BP_BLENDMODE_SUBTRACT_END = 20,
    GX_BP_BLENDMODE_LOGICMODE_ST = 16,
    GX_BP_BLENDMODE_LOGICMODE_END = 19,
} GXBPBlendMode;

typedef enum _GXBPZMode {
    GX_BP_ZMODE_TEST_ENABLE_ST = 31,
    GX_BP_ZMODE_TEST_ENABLE_END = 31,
    GX_BP_ZMODE_COMPARE_ST = 28,
    GX_BP_ZMODE_COMPARE_END = 30,
    GX_BP_ZMODE_UPDATE_ENABLE_ST = 27,
    GX_BP_ZMODE_UPDATE_ENABLE_END = 27,
} GXBPZMode;

typedef enum _GXBPZControl {
    GX_BP_ZCONTROL_PIXEL_FMT_ST = 29,
    GX_BP_ZCONTROL_PIXEL_FMT_END = 31,
    GX_BP_ZCONTROL_Z_FMT_ST = 26,
    GX_BP_ZCONTROL_Z_FMT_END = 28,
    GX_BP_ZCONTROL_BEFORE_TEX_ST = 25,
    GX_BP_ZCONTROL_BEFORE_TEX_END = 25,
} GXBPZControl;

typedef enum _GXBPDstAlpha {
    GX_BP_DSTALPHA_ALPHA_ST = 24,
    GX_BP_DSTALPHA_ALPHA_END = 31,
    GX_BP_DSTALPHA_ENABLE_ST = 23,
    GX_BP_DSTALPHA_ENABLE_END = 23,
    GX_BP_DSTALPHA_YUV_FMT_ST = 21,
    GX_BP_DSTALPHA_YUV_FMT_END = 22,
} GXBPDstAlpha;

typedef enum _GXBPFieldMask {
    GX_BP_FIELDMASK_ODD_ST = 31,
    GX_BP_FIELDMASK_ODD_END = 31,
    GX_BP_FIELDMASK_EVEN_ST = 30,
    GX_BP_FIELDMASK_EVEN_END = 30,
} GXBPFieldMask;

typedef enum _GXBPLinePtWidth {
    GX_BP_LINEPTWIDTH_LINESZ_ST = 24,
    GX_BP_LINEPTWIDTH_LINESZ_END = 31,
    GX_BP_LINEPTWIDTH_POINTSZ_ST = 16,
    GX_BP_LINEPTWIDTH_POINTSZ_END = 23,
    GX_BP_LINEPTWIDTH_LINEOFS_ST = 13,
    GX_BP_LINEPTWIDTH_LINEOFS_END = 15,
    GX_BP_LINEPTWIDTH_POINTOFS_ST = 10,
    GX_BP_LINEPTWIDTH_POINTOFS_END = 12,
    GX_BP_LINEPTWIDTH_ADJUST_ST = 9,
    GX_BP_LINEPTWIDTH_ADJUST_END = 9,
} GXBPLinePtWidth;

typedef enum _GXXfMem {
    GX_XF_MEM_POSMTX = 0x000,
    GX_XF_MEM_NRMMTX = 0x400,
    GX_XF_MEM_DUALTEXMTX = 0x500,
    GX_XF_MEM_LIGHTOBJ = 0x600,
} GXXfMem;

typedef enum _GXBPScissorTL {
    GX_BP_SCISSORTL_TOP_ST = 21,
    GX_BP_SCISSORTL_TOP_END = 31,
    GX_BP_SCISSORTL_LEFT_ST = 9,
    GX_BP_SCISSORTL_LEFT_END = 19,
} GXBPScissorTL;

typedef enum _GXBPScissorBR {
    GX_BP_SCISSORBR_BOT_ST = 21,
    GX_BP_SCISSORBR_BOT_END = 31,
    GX_BP_SCISSORBR_RIGHT_ST = 9,
    GX_BP_SCISSORBR_RIGHT_END = 19,
} GXBPScissorBR;

typedef enum _GXBPScissorOffset {
    GX_BP_SCISSOROFS_OX_ST = 22,
    GX_BP_SCISSOROFS_OX_END = 31,
    GX_BP_SCISSOROFS_OY_ST = 12,
    GX_BP_SCISSOROFS_OY_END = 21,
} GXBPScissorOffset;

typedef enum _GXXFClr0Ctrl {
    GX_XF_CLR0CTRL_MTXSRC_ST = 31,
    GX_XF_CLR0CTRL_MTXSRC_END = 31,
    GX_XF_CLR0CTRL_LIGHT_ST = 30,
    GX_XF_CLR0CTRL_LIGHT_END = 30,
    GX_XF_CLR0CTRL_LMASKHI_ST = 26,
    GX_XF_CLR0CTRL_LMASKHI_END = 29,
    GX_XF_CLR0CTRL_AMBSRC_ST = 25,
    GX_XF_CLR0CTRL_AMBSRC_END = 25,
    GX_XF_CLR0CTRL_DIFATTN_ST = 23,
    GX_XF_CLR0CTRL_DIFATTN_END = 24,
    GX_XF_CLR0CTRL_ATTNENABLE_ST = 22,
    GX_XF_CLR0CTRL_ATTNENABLE_END = 22,
    GX_XF_CLR0CTRL_ATTNSEL_ST = 21,
    GX_XF_CLR0CTRL_ATTNSEL_END = 21,
    GX_XF_CLR0CTRL_LMASKLO_ST = 17,
    GX_XF_CLR0CTRL_LMASKLO_END = 20,
} GXXFClr0Ctrl;


// Enumerators the decomp spells differently from aurora (same enum type and value).
#ifndef GX_TEXMAP_DISABLE
#define GX_TEXMAP_DISABLE GX_TEX_DISABLE
#endif
#ifndef GX_MAXCOORD
#define GX_MAXCOORD GX_MAX_TEXCOORD
#endif
#ifndef GX_BL_SRC_COLOR
#define GX_BL_SRC_COLOR GX_BL_SRCCLR
#endif
#ifndef GX_BL_DST_COLOR
#define GX_BL_DST_COLOR GX_BL_SRCCLR
#endif
#ifndef GX_BL_INV_SRC_COLOR
#define GX_BL_INV_SRC_COLOR GX_BL_INVSRCCLR
#endif
#ifndef GX_BL_INV_DST_COLOR
#define GX_BL_INV_DST_COLOR GX_BL_INVSRCCLR
#endif
#ifndef GX_BL_SRC_ALPHA
#define GX_BL_SRC_ALPHA GX_BL_SRCALPHA
#endif
#ifndef GX_BL_INV_SRC_ALPHA
#define GX_BL_INV_SRC_ALPHA GX_BL_INVSRCALPHA
#endif
#ifndef GX_BL_DST_ALPHA
#define GX_BL_DST_ALPHA GX_BL_DSTALPHA
#endif
#ifndef GX_BL_INV_DST_ALPHA
#define GX_BL_INV_DST_ALPHA GX_BL_INVDSTALPHA
#endif
#ifndef GX_LO_REV_AND
#define GX_LO_REV_AND GX_LO_REVAND
#endif
#ifndef GX_LO_INV_AND
#define GX_LO_INV_AND GX_LO_INVAND
#endif
#ifndef GX_LO_REV_OR
#define GX_LO_REV_OR GX_LO_REVOR
#endif
#ifndef GX_LO_INV_COPY
#define GX_LO_INV_COPY GX_LO_INVCOPY
#endif
#ifndef GX_LO_INV_OR
#define GX_LO_INV_OR GX_LO_INVOR
#endif
#ifndef GX_COMPCNT_NULL
#define GX_COMPCNT_NULL GX_POS_XY
#endif
#ifndef GX_COMP_NULL
#define GX_COMP_NULL GX_U8
#endif
#ifndef GX_MAX_TLUT
#define GX_MAX_TLUT GX_BIGTLUT0
#endif
#ifndef GX_MAX_BIGTLUT
#define GX_MAX_BIGTLUT GX_TLUT4
#endif
#ifndef GX_MAX_TEXWRAP_MODE
#define GX_MAX_TEXWRAP_MODE GX_MAX_TEXWRAPMODE
#endif

#endif
