//
// Generated by dtk
// Translation Unit: f_pc_profile.cpp
//

#include "f_pc/f_pc_profile.h"

#if TARGET_PC
// Statically linked on PC; the f_pc_profile_lst REL's prolog used to set this.
extern process_profile_definition* g_fpcPfLst_ProfileList[];
process_profile_definition** g_fpcPf_ProfileList_p = g_fpcPfLst_ProfileList;
#else
process_profile_definition** g_fpcPf_ProfileList_p;
#endif

/* 8004003C-80040050       .text fpcPf_Get__Fs */
process_profile_definition* fpcPf_Get(s16 i_profName) {
    int profName = i_profName;
    return g_fpcPf_ProfileList_p[profName];
}
