// Generated by tools/gen_audio_null.py from ww_audio_null.symbols. Do not edit.
// No-op audio until JAudio/JAZelAudio are ported: each function the game links against does
// nothing, except where the game waits on audio being ready.

#include "JAZelAudio/JAIZelBasic.h"
#include "JAZelAudio/JAIZelInst.h"
#include "JAZelAudio/JAIZelAnime.h"
#include "JSystem/JAudio/JAIAnimation.h"
#include "JSystem/JAudio/JAIBankWave.h"
#include "JSystem/JAudio/JAIBasic.h"
#include "JSystem/JAudio/JAIGlobalParameter.h"
#include "JSystem/JAudio/JAISequenceMgr.h"
#include "JSystem/JAudio/JAISound.h"
#include "JSystem/JAudio/JAIStreamMgr.h"
#include "JSystem/JAudio/JASDvdThread.h"
#include "JSystem/JStudio/JStudio_JAudio/control.h"

bool JAInter::BankWave::checkAllWaveLoadStatus() { return {}; }
int JASystem::Dvd::sendCmdMsg(int (*)(void *),void *,unsigned int) { return {}; }
JAIAnimeSound::JAIAnimeSound() {}
JAIBasic::JAIBasic() {}
JAIZelBasic::JAIZelBasic() { zel_basic = this; }
JAIZelInst::JAIZelInst() {}
bool JAIBasic::allocStreamBuffer(void *,int) { return {}; }
bool JAIBasic::deallocStreamBuffer() { return {}; }
class JAISound * * JAIZelBasic::seStart(unsigned int,struct Vec *,unsigned int,signed char,float,float,float,float,unsigned char) { return {}; }
float JAIZelInst::getMelodyPattern(int,int,int *) { return {}; }
int JAIZelBasic::check1stDynamicWave() { return {}; }
int JAIZelBasic::checkFirstWaves() { return {}; }
int JAIZelBasic::checkPlayingMainBgmFlag() { return {}; }
int JAIZelBasic::checkPlayingSubBgmFlag() { return {}; }
int JAIZelInst::judge(int,int) { return {}; }
int JAIZelInst::metronomePlay(int,int) { return {}; }
int JAIZelInst::setStickPos(int,int) { return {}; }
class JAIZelBasic * JAIZelBasic::zel_basic;
unsigned char JAIZelBasic::getLinkVoiceVowel(unsigned int) { return {}; }
JStudio_JAudio::TCreateObject::~TCreateObject() {}
bool JStudio_JAudio::TCreateObject::create(class JStudio::TObject * *,class JStudio::stb::data::TParse_TBlock_object const &) { return {}; }
class JAISound * JAIBasic::makeSound(unsigned int) { return {}; }
class JAISound * JAIZelBasic::makeSound(unsigned int) { return {}; }
float JAIBasic::getMapInfoFxParameter(unsigned int) { return {}; }
float JAIZelBasic::getMapInfoFxParameter(unsigned int) { return {}; }
int JAIBasic::getMapInfoFxline(unsigned int) { return {}; }
int JAIBasic::getMapInfoGround(unsigned int) { return {}; }
int JAIZelBasic::getMapInfoFxline(unsigned int) { return {}; }
int JAIZelBasic::getMapInfoGround(unsigned int) { return {}; }
void JAIAnimeSound::setSpeedModifySound(class JAISound *,struct JAIAnimeFrameSoundData *,float) {}
void JAIAnimeSound::startAnimSound(void *,unsigned int,class JAISound * *,class JAInter::Actor *,unsigned char) {}
void JAIBasic::initStream() {}
void JAIBasic::setRegisterTrackCallback() {}
void JAIBasic::setSeExtParameter(class JAISound *) {}
void JAIZelAnime::setSpeedModifySound(class JAISound *,struct JAIAnimeFrameSoundData *,float) {}
void JAIZelAnime::startAnimSound(void *,unsigned int,class JAISound * *,class JAInter::Actor *,unsigned char) {}
void JAIAnimeSound::initActorAnimSound(void *,unsigned int,float) {}
void JAIAnimeSound::stop() {}
void JAIZelAnime::setAnimSound(struct Vec *,float,float,unsigned int,signed char) {}
void JAIZelAnime::setPlayPosition(float) {}
void JAIZelBasic::bgmHitSound(int) {}
void JAIZelBasic::bgmMuteMtDragon() {}
void JAIZelBasic::bgmNowBattle(float) {}
void JAIZelBasic::bgmNowKaitengiri() {}
void JAIZelBasic::bgmSetSwordUsing(int) {}
void JAIZelBasic::bgmStart(unsigned int,unsigned int,int) {}
void JAIZelBasic::bgmStop(unsigned int,int) {}
void JAIZelBasic::bgmStreamPlay() {}
void JAIZelBasic::bgmStreamPrepare(unsigned int) {}
void JAIZelBasic::endLandingDemo() {}
void JAIZelBasic::getCameraInfo(struct Vec *,float (*)[4],unsigned int) {}
void JAIZelBasic::getCameraMapInfo(unsigned int) {}
void JAIZelBasic::gframeProcess() {}
void JAIZelBasic::heartGaugeOn() {}
void JAIZelBasic::init(class JKRSolidHeap *,unsigned int) {}
void JAIZelBasic::initRiverPos() {}
void JAIZelBasic::initSeaEnvPos() {}
void JAIZelBasic::initWindowPos() {}
void JAIZelBasic::linkVoiceStart(unsigned int,struct Vec *,unsigned char,signed char) {}
void JAIZelBasic::load1stDynamicWave() {}
void JAIZelBasic::load2ndDynamicWave() {}
void JAIZelBasic::loadStaticWaves() {}
void JAIZelBasic::messageSePlay(unsigned short,struct Vec *,signed char) {}
void JAIZelBasic::monsSeInit() {}
void JAIZelBasic::onEnemyDamage() {}
void JAIZelBasic::prepareLandingDemo(int) {}
void JAIZelBasic::rainPlay(int) {}
void JAIZelBasic::registRiverPos(struct Vec *) {}
void JAIZelBasic::registSeaEnvPos(struct Vec *) {}
void JAIZelBasic::registWindowPos(struct Vec *) {}
void JAIZelBasic::resetProcess() {}
void JAIZelBasic::resetRecover() {}
void JAIZelBasic::riverSePlay(unsigned char,signed char) {}
void JAIZelBasic::sceneBgmStart() {}
void JAIZelBasic::seDeleteObject(struct Vec *) {}
void JAIZelBasic::seStop(unsigned int,int) {}
void JAIZelBasic::seStopActor(struct Vec *,unsigned int) {}
void JAIZelBasic::seaEnvSePlay(unsigned int,signed char) {}
void JAIZelBasic::seaShoreSE(unsigned int,struct Vec *,unsigned int,signed char) {}
void JAIZelBasic::setCameraGroupInfo(unsigned char) {}
void JAIZelBasic::setCameraPolygonPos(struct Vec *) {}
void JAIZelBasic::setEventBit(void *) {}
void JAIZelBasic::setLinkBootsType(int) {}
void JAIZelBasic::setLinkGroupInfo(unsigned char) {}
void JAIZelBasic::setLinkHp(int,int) {}
void JAIZelBasic::setLinkOnBoard(int) {}
void JAIZelBasic::setLinkShieldType(int,int) {}
void JAIZelBasic::setLinkSwordType(int,int) {}
void JAIZelBasic::setOutputMode(unsigned int) {}
void JAIZelBasic::setSceneName(char *,int,int) {}
void JAIZelBasic::stSkyCloisters() {}
void JAIZelBasic::startLandingDemo() {}
void JAIZelBasic::subBgmStart(unsigned int) {}
void JAIZelBasic::subBgmStop() {}
void JAIZelBasic::taktModeMute() {}
void JAIZelBasic::taktModeMuteOff() {}
void JAIZelBasic::talkIn() {}
void JAIZelBasic::talkOut() {}
void JAIZelBasic::waterfallSePlay(unsigned char,struct Vec *,signed char) {}
void JAIZelInst::ambientPlay() {}
void JAIZelInst::armSoundPlay(int) {}
void JAIZelInst::melodyPlay(int) {}
void JAIZelInst::melodyStop() {}
void JAIZelInst::play() {}
void JAIZelInst::playArmSwing(int,int) {}
void JAIZelInst::reset() {}
void JAIZelInst::setBeat(int) {}
void JAIZelInst::setVolume(float) {}
void JAIZelInst::stopArmSwing() {}
unsigned int JAInter::StreamLib::getNeedBufferSize() { return {}; }
void JAIGlobalParameter::setParamInitDataPointer(void *) {}
void JAIGlobalParameter::setParamStreamDecodedBufferBlocks(unsigned int) {}
void JAIGlobalParameter::setParamStreamInsideBufferCut(bool) {}
void JAInter::SequenceMgr::getArchiveName(char *) {}
void JAInter::SequenceMgr::setArchivePointer(class JKRArchive *) {}
void JAInter::StreamLib::setAllocBufferCallback(void (*)(void)) {}
void JAInter::StreamLib::setDeallocBufferCallback(void (*)(void)) {}
void JAInter::StreamLib::stop() {}
