// Generated by tools/gen_profile_list.py from src/f_pc/f_pc_profile_lst.cpp. Do not edit.
// The process profile list, indexed by process name. Profiles of actors that are not built
// (WW_ENABLED_RELS in files.cmake) are nullptr.

#include "f_pc/f_pc_profile.h"
#include "f_op/f_op_actor.h"
#include "f_op/f_op_camera.h"
#include "f_op/f_op_kankyo.h"
#include "f_op/f_op_msg_mng.h"
#include "f_op/f_op_overlap_mng.h"
#include "f_op/f_op_scene.h"

extern actor_process_profile_definition g_profile_AGB;
extern actor_process_profile_definition g_profile_ARROW;
extern actor_process_profile_definition g_profile_BOOMERANG;
extern actor_process_profile_definition g_profile_BRIDGE;
extern actor_process_profile_definition g_profile_Bomb2;
extern actor_process_profile_definition g_profile_DEMO00;
extern actor_process_profile_definition g_profile_DISAPPEAR;
extern actor_process_profile_definition g_profile_ESA;
extern actor_process_profile_definition g_profile_GRASS;
extern actor_process_profile_definition g_profile_GRID;
extern actor_process_profile_definition g_profile_HIMO2;
extern actor_process_profile_definition g_profile_HOOKSHOT;
extern actor_process_profile_definition g_profile_ITEM;
extern actor_process_profile_definition g_profile_Iball;
extern actor_process_profile_definition g_profile_KAMOME;
extern actor_process_profile_definition g_profile_KANBAN;
extern actor_process_profile_definition g_profile_KB;
extern actor_process_profile_definition g_profile_KN;
extern actor_process_profile_definition g_profile_KNOB00;
extern actor_process_profile_definition g_profile_KYTAG01;
extern actor_process_profile_definition g_profile_Lwood;
extern actor_process_profile_definition g_profile_NH;
extern actor_process_profile_definition g_profile_NPC_FA1;
extern actor_process_profile_definition g_profile_OBJ_IKADA;
extern actor_process_profile_definition g_profile_OBJ_SEARCH;
extern actor_process_profile_definition g_profile_OBJ_TORIPOST;
extern actor_process_profile_definition g_profile_Obj_Lpalm;
extern actor_process_profile_definition g_profile_Obj_Wood;
extern actor_process_profile_definition g_profile_SEA;
extern actor_process_profile_definition g_profile_SHIP;
extern actor_process_profile_definition g_profile_SPC_ITEM01;
extern actor_process_profile_definition g_profile_STANDITEM;
extern actor_process_profile_definition g_profile_Stone2;
extern actor_process_profile_definition g_profile_THROWSTONE;
extern actor_process_profile_definition g_profile_TITLE;
extern actor_process_profile_definition g_profile_TSUBO;
extern actor_process_profile_definition g_profile_VRBOX2;
extern actor_process_profile_definition g_profile_VRBOX;
extern actor_process_profile_definition2 g_profile_BG;
extern actor_process_profile_definition2 g_profile_PLAYER;
extern camera_process_profile_definition g_profile_CAMERA2;
extern camera_process_profile_definition g_profile_CAMERA;
extern kankyo_process_profile_definition g_profile_ENVSE;
extern kankyo_process_profile_definition g_profile_KANKYO;
extern kankyo_process_profile_definition g_profile_KYEFF2;
extern kankyo_process_profile_definition g_profile_KYEFF;
extern kankyo_process_profile_definition g_profile_KY_THUNDER;
extern kankyo_process_profile_definition g_profile_LEVEL_SE;
extern kankyo_process_profile_definition g_profile_WATER_MARK;
extern kankyo_process_profile_definition g_profile_WIND_ARROW;
extern kankyo_process_profile_definition g_profile_WPILLAR;
extern kankyo_process_profile_definition g_profile_WPOT_WATER;
extern msg_process_profile_definition g_profile_AUCTION_SCREEN;
extern msg_process_profile_definition g_profile_GAMEOVER;
extern msg_process_profile_definition g_profile_MENUWINDOW;
extern msg_process_profile_definition g_profile_MESG;
extern msg_process_profile_definition g_profile_METER;
extern msg_process_profile_definition g_profile_MINIGAME_STARTER;
extern msg_process_profile_definition g_profile_MINIGAME_TERMINATER;
extern msg_process_profile_definition g_profile_MSG2;
extern msg_process_profile_definition g_profile_MSG3;
extern msg_process_profile_definition g_profile_MSG;
extern msg_process_profile_definition g_profile_Menu_Cloth;
extern msg_process_profile_definition g_profile_OPERATE_WIND;
extern msg_process_profile_definition g_profile_PB;
extern msg_process_profile_definition g_profile_PLACE_NAME;
extern msg_process_profile_definition g_profile_SCP;
extern msg_process_profile_definition g_profile_TIMER;
extern overlap_process_profile_definition g_profile_OVERLAP0;
extern overlap_process_profile_definition g_profile_OVERLAP1;
extern overlap_process_profile_definition g_profile_OVERLAP2;
extern overlap_process_profile_definition g_profile_OVERLAP3;
extern overlap_process_profile_definition g_profile_OVERLAP4;
extern overlap_process_profile_definition g_profile_OVERLAP5;
extern overlap_process_profile_definition g_profile_OVERLAP6;
extern overlap_process_profile_definition g_profile_OVERLAP7;
extern overlap_process_profile_definition g_profile_OVERLAP8;
extern scene_process_profile_definition g_profile_ENDING_SCENE;
extern scene_process_profile_definition g_profile_LOGO_SCENE;
extern scene_process_profile_definition g_profile_MENU_SCENE;
extern scene_process_profile_definition g_profile_NAMEEX_SCENE;
extern scene_process_profile_definition g_profile_NAME_SCENE;
extern scene_process_profile_definition g_profile_OPEN2_SCENE;
extern scene_process_profile_definition g_profile_OPENING2_SCENE;
extern scene_process_profile_definition g_profile_OPENING_SCENE;
extern scene_process_profile_definition g_profile_OPEN_SCENE;
extern scene_process_profile_definition g_profile_PLAY_SCENE;
extern scene_process_profile_definition g_profile_ROOM_SCENE;
extern scene_process_profile_definition g_profile_TITLE_SCENE;

process_profile_definition* g_fpcPfLst_ProfileList[] = {
    reinterpret_cast<process_profile_definition*>(&g_profile_OVERLAP0),
    reinterpret_cast<process_profile_definition*>(&g_profile_OVERLAP1),
    reinterpret_cast<process_profile_definition*>(&g_profile_OVERLAP6),
    reinterpret_cast<process_profile_definition*>(&g_profile_OVERLAP7),
    reinterpret_cast<process_profile_definition*>(&g_profile_OVERLAP8),
    reinterpret_cast<process_profile_definition*>(&g_profile_LOGO_SCENE),
    reinterpret_cast<process_profile_definition*>(&g_profile_MENU_SCENE),
    reinterpret_cast<process_profile_definition*>(&g_profile_PLAY_SCENE),
    reinterpret_cast<process_profile_definition*>(&g_profile_OPENING_SCENE),
    reinterpret_cast<process_profile_definition*>(&g_profile_OPENING2_SCENE),
    reinterpret_cast<process_profile_definition*>(&g_profile_TITLE_SCENE),
    reinterpret_cast<process_profile_definition*>(&g_profile_ENDING_SCENE),
    reinterpret_cast<process_profile_definition*>(&g_profile_NAME_SCENE),
    reinterpret_cast<process_profile_definition*>(&g_profile_NAMEEX_SCENE),
    reinterpret_cast<process_profile_definition*>(&g_profile_OPEN_SCENE),
    reinterpret_cast<process_profile_definition*>(&g_profile_OPEN2_SCENE),
    reinterpret_cast<process_profile_definition*>(&g_profile_OVERLAP2),
    reinterpret_cast<process_profile_definition*>(&g_profile_OVERLAP3),
    reinterpret_cast<process_profile_definition*>(&g_profile_OVERLAP4),
    reinterpret_cast<process_profile_definition*>(&g_profile_OVERLAP5),
    reinterpret_cast<process_profile_definition*>(&g_profile_ROOM_SCENE),
    reinterpret_cast<process_profile_definition*>(&g_profile_KANKYO),
    nullptr,  // g_profile_ALLDIE (d_a_alldie not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_ENVSE),
    reinterpret_cast<process_profile_definition*>(&g_profile_WIND_ARROW),
    reinterpret_cast<process_profile_definition*>(&g_profile_WPOT_WATER),
    reinterpret_cast<process_profile_definition*>(&g_profile_LEVEL_SE),
    reinterpret_cast<process_profile_definition*>(&g_profile_THROWSTONE),
    nullptr,  // g_profile_TAG_EVSW (d_a_tag_evsw not built)
    nullptr,  // g_profile_Obj_Swpush (d_a_obj_swpush not built)
    nullptr,  // g_profile_Obj_Swheavy (d_a_obj_swheavy not built)
    nullptr,  // g_profile_Obj_Swflat (d_a_obj_swflat not built)
    nullptr,  // g_profile_Obj_Swlight (d_a_obj_swlight not built)
    nullptr,  // g_profile_Obj_Swhammer (d_a_obj_swhammer not built)
    nullptr,  // g_profile_Obj_Quake (d_a_obj_quake not built)
    nullptr,  // g_profile_Obj_Drift (d_a_obj_drift not built)
    nullptr,  // g_profile_Tag_Volcano (d_a_tag_volcano not built)
    nullptr,  // g_profile_TAG_SO (d_a_tag_so not built)
    nullptr,  // g_profile_Obj_Pbco (d_a_obj_pbco not built)
    nullptr,  // g_profile_SEATAG (d_a_seatag not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_SEA),
    nullptr,  // g_profile_Obj_Tide (d_a_obj_tide not built)
    nullptr,  // g_profile_Hmlif (d_a_hmlif not built)
    nullptr,  // g_profile_SCENECHG (d_a_scene_change not built)
    nullptr,  // g_profile_Obj_Magmarock (d_a_obj_magmarock not built)
    nullptr,  // g_profile_Obj_Movebox (d_a_obj_movebox not built)
    nullptr,  // g_profile_Obj_Tribox (d_a_obj_tribox not built)
    nullptr,  // g_profile_Obj_Shelf (d_a_obj_shelf not built)
    nullptr,  // g_profile_Obj_Hlift (d_a_obj_hlift not built)
    nullptr,  // g_profile_Obj_Hami2 (d_a_obj_hami2 not built)
    nullptr,  // g_profile_Obj_Hami3 (d_a_obj_hami3 not built)
    nullptr,  // g_profile_Obj_Hami4 (d_a_obj_hami4 not built)
    nullptr,  // g_profile_Obj_Hbrf1 (d_a_obj_hbrf1 not built)
    nullptr,  // g_profile_Obj_Volcano (d_a_obj_volcano not built)
    nullptr,  // g_profile_Obj_Vmc (d_a_obj_vmc not built)
    nullptr,  // g_profile_Obj_Usovmc (d_a_obj_usovmc not built)
    nullptr,  // g_profile_Obj_Vfan (d_a_obj_vfan not built)
    nullptr,  // g_profile_Obj_Iceisland (d_a_obj_iceisland not built)
    nullptr,  // g_profile_Obj_Dragonhead (d_a_obj_dragonhead not built)
    nullptr,  // g_profile_Obj_Pirateship (d_a_obj_pirateship not built)
    nullptr,  // g_profile_Obj_Tousekiki (d_a_obj_tousekiki not built)
    nullptr,  // g_profile_Tag_Ret (d_a_tag_ret not built)
    nullptr,  // g_profile_Kaji (d_a_kaji not built)
    nullptr,  // g_profile_Canon (d_a_canon not built)
    nullptr,  // g_profile_MGBOARD (d_a_mgameboard not built)
    nullptr,  // g_profile_OBJ_CANON (d_a_obj_canon not built)
    nullptr,  // g_profile_OBJ_OTBLE (d_a_obj_otble not built)
    nullptr,  // g_profile_OBJ_WARPT (d_a_obj_warpt not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_OBJ_SEARCH),
    reinterpret_cast<process_profile_definition*>(&g_profile_OBJ_TORIPOST),
    reinterpret_cast<process_profile_definition*>(&g_profile_OBJ_IKADA),
    nullptr,  // g_profile_OBJ_MJDOOR (d_a_obj_majyuu_door not built)
    nullptr,  // g_profile_OBJ_PFALL (d_a_obj_pfall not built)
    nullptr,  // g_profile_OBJ_HOLE (d_a_obj_hole not built)
    nullptr,  // g_profile_Obj_Stair (d_a_obj_stair not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_Obj_Lpalm),
    nullptr,  // g_profile_Obj_Mtest (d_a_obj_mtest not built)
    nullptr,  // g_profile_Obj_Mkie (d_a_obj_mkie not built)
    nullptr,  // g_profile_Obj_Mkiek (d_a_obj_mkiek not built)
    nullptr,  // g_profile_Obj_MknjD (d_a_obj_mknjd not built)
    nullptr,  // g_profile_Obj_Msdan (d_a_obj_msdan not built)
    nullptr,  // g_profile_Obj_MsdanSub (d_a_obj_msdan_sub not built)
    nullptr,  // g_profile_Obj_Msdan2 (d_a_obj_msdan2 not built)
    nullptr,  // g_profile_Obj_MsdanSub2 (d_a_obj_msdan_sub2 not built)
    nullptr,  // g_profile_Obj_Nest (d_a_obj_nest not built)
    nullptr,  // g_profile_Obj_Ojtree (d_a_obj_ojtree not built)
    nullptr,  // g_profile_Obj_Ospbox (d_a_obj_ospbox not built)
    nullptr,  // g_profile_Obj_Ladder (d_a_obj_ladder not built)
    nullptr,  // g_profile_Obj_Smplbg (d_a_obj_smplbg not built)
    nullptr,  // g_profile_Obj_Akabe (d_a_obj_akabe not built)
    nullptr,  // g_profile_Obj_Ashut (d_a_obj_ashut not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_BRIDGE),
    nullptr,  // g_profile_MSW (d_a_msw not built)
    nullptr,  // g_profile_MFLFT (d_a_mflft not built)
    nullptr,  // g_profile_KLFT (d_a_klft not built)
    nullptr,  // g_profile_ICE_LIFT (d_a_icelift not built)
    nullptr,  // g_profile_AMI_PROP (d_a_amiprop not built)
    nullptr,  // g_profile_PEDESTAL (d_a_pedestal not built)
    nullptr,  // g_profile_FLOOR (d_a_floor not built)
    nullptr,  // g_profile_KITA (d_a_kita not built)
    nullptr,  // g_profile_KOKIIE (d_a_kokiie not built)
    nullptr,  // g_profile_SHAND (d_a_shand not built)
    nullptr,  // g_profile_BITA (d_a_bita not built)
    nullptr,  // g_profile_SK (d_a_sk not built)
    nullptr,  // g_profile_SK2 (d_a_sk2 not built)
    nullptr,  // g_profile_SSK (d_a_ssk not built)
    nullptr,  // g_profile_WARPFLOWER (d_a_warpf not built)
    nullptr,  // g_profile_WARPFOUT (d_a_warpfout not built)
    nullptr,  // g_profile_WARPLIGHT (d_a_warpls not built)
    nullptr,  // g_profile_WARPHYRULE (d_a_warphr not built)
    nullptr,  // g_profile_WARPDEMO20 (d_a_warpdm20 not built)
    nullptr,  // g_profile_WARPGANON (d_a_warpgn not built)
    nullptr,  // g_profile_WARPMAJYUU (d_a_warpmj not built)
    nullptr,  // g_profile_Balancelift (d_a_obj_balancelift not built)
    nullptr,  // g_profile_SHUTTER (d_a_shutter not built)
    nullptr,  // g_profile_SHUTTER2 (d_a_shutter2 not built)
    nullptr,  // g_profile_WINDMILL (d_a_windmill not built)
    nullptr,  // g_profile_MBDOOR (d_a_mbdoor not built)
    nullptr,  // g_profile_NPC_DE1 (d_a_npc_de1 not built)
    nullptr,  // g_profile_NPC_NZ (d_a_npc_nz not built)
    nullptr,  // g_profile_NPC_SO (d_a_npc_so not built)
    nullptr,  // g_profile_FM (d_a_fm not built)
    nullptr,  // g_profile_LEAF_LIFT (d_a_leaflift not built)
    nullptr,  // g_profile_Obj_Roten (d_a_obj_roten not built)
    nullptr,  // g_profile_TOGE (d_a_toge not built)
    nullptr,  // g_profile_Obj_Ferris (d_a_obj_ferris not built)
    nullptr,  // g_profile_Obj_Xfuta (d_a_obj_xfuta not built)
    nullptr,  // g_profile_Obj_Gaship (d_a_obj_gaship not built)
    nullptr,  // g_profile_Obj_Rforce (d_a_obj_rforce not built)
    nullptr,  // g_profile_Obj_Gaship2 (d_a_obj_gaship2 not built)
    nullptr,  // g_profile_Obj_Light (d_a_obj_light not built)
    nullptr,  // g_profile_Obj_Homen (d_a_obj_homen not built)
    nullptr,  // g_profile_Obj_Homensmk (d_a_obj_homensmoke not built)
    nullptr,  // g_profile_Obj_Ftree (d_a_obj_ftree not built)
    nullptr,  // g_profile_Obj_Vds (d_a_obj_Vds not built)
    nullptr,  // g_profile_Obj_Vyasi (d_a_obj_vyasi not built)
    nullptr,  // g_profile_Obj_Ajav (d_a_obj_ajav not built)
    nullptr,  // g_profile_Obj_Trap (d_a_obj_trap not built)
    nullptr,  // g_profile_Obj_Hha (d_a_obj_hha not built)
    nullptr,  // g_profile_Obj_Htetu1 (d_a_obj_htetu1 not built)
    nullptr,  // g_profile_Obj_Gnntakis (d_a_obj_gnndemotakis not built)
    nullptr,  // g_profile_Obj_Gnntakie (d_a_obj_gnndemotakie not built)
    nullptr,  // g_profile_Obj_Gnnbtaki (d_a_obj_gnnbtltaki not built)
    nullptr,  // g_profile_Obj_Rcloud (d_a_obj_rcloud not built)
    nullptr,  // g_profile_Obj_Gryw00 (d_a_obj_gryw00 not built)
    nullptr,  // g_profile_Obj_AjavW (d_a_obj_AjavW not built)
    nullptr,  // g_profile_Obj_Leaves (d_a_obj_leaves not built)
    nullptr,  // g_profile_Obj_YLzou (d_a_obj_YLzou not built)
    nullptr,  // g_profile_Obj_Gbed (d_a_obj_ganonbed not built)
    nullptr,  // g_profile_Obj_Vteng (d_a_obj_Vteng not built)
    nullptr,  // g_profile_Obj_Hfuck1 (d_a_obj_hfuck1 not built)
    nullptr,  // g_profile_Obj_Ohatch (d_a_obj_ohatch not built)
    nullptr,  // g_profile_Obj_Hcbh (d_a_obj_hcbh not built)
    nullptr,  // g_profile_Obj_Ygush00 (d_a_obj_Ygush00 not built)
    nullptr,  // g_profile_Obj_Bscurtain (d_a_obj_bscurtain not built)
    nullptr,  // g_profile_Obj_Shmrgrd (d_a_obj_shmrgrd not built)
    nullptr,  // g_profile_Obj_Eayogn (d_a_obj_eayogn not built)
    nullptr,  // g_profile_Obj_Vmsms (d_a_obj_vmsms not built)
    nullptr,  // g_profile_Obj_Vmsdz (d_a_obj_vmsdz not built)
    nullptr,  // g_profile_Ygcwp (d_a_ygcwp not built)
    nullptr,  // g_profile_Obj_Vgnfd (d_a_obj_vgnfd not built)
    nullptr,  // g_profile_Obj_Kanoke (d_a_obj_kanoke not built)
    nullptr,  // g_profile_Obj_Eskban (d_a_obj_eskban not built)
    nullptr,  // g_profile_Obj_Ekskz (d_a_obj_ekskz not built)
    nullptr,  // g_profile_Obj_Ebomzo (d_a_obj_ebomzo not built)
    nullptr,  // g_profile_Obj_Kanat (d_a_obj_kanat not built)
    nullptr,  // g_profile_Obj_Aygr (d_a_obj_aygr not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_SHIP),
    nullptr,  // g_profile_Obj_Jump (d_a_obj_jump not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_PLAYER),
    reinterpret_cast<process_profile_definition*>(&g_profile_HOOKSHOT),
    nullptr,  // g_profile_NPC_MK (d_a_npc_mk not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_GRID),
    nullptr,  // g_profile_SAIL (d_a_sail not built)
    nullptr,  // g_profile_PIRATE_FLAG (d_a_pirate_flag not built)
    nullptr,  // g_profile_MAJUU_FLAG (d_a_majuu_flag not built)
    nullptr,  // g_profile_Tori_Flag (d_a_tori_flag not built)
    nullptr,  // g_profile_Sie_Flag (d_a_sie_flag not built)
    nullptr,  // g_profile_SYAN (d_a_syan not built)
    nullptr,  // g_profile_AYUSH (d_a_ghostship not built)
    nullptr,  // g_profile_OSHIP (d_a_oship not built)
    nullptr,  // g_profile_RECTANGLE (d_a_rectangle not built)
    nullptr,  // g_profile_BB (d_a_bb not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_KANBAN),
    nullptr,  // g_profile_HITOBJ (d_a_hitobj not built)
    nullptr,  // g_profile_KT (d_a_kt not built)
    nullptr,  // g_profile_EP (d_a_ep not built)
    nullptr,  // g_profile_LAMP (d_a_lamp not built)
    nullptr,  // g_profile_FF (d_a_ff not built)
    nullptr,  // g_profile_MO2 (d_a_mo2 not built)
    nullptr,  // g_profile_BK (d_a_bk not built)
    nullptr,  // g_profile_ST (d_a_st not built)
    nullptr,  // g_profile_TN (d_a_tn not built)
    nullptr,  // g_profile_MANT (d_a_mant not built)
    nullptr,  // g_profile_KANTERA (d_a_kantera not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_KAMOME),
#if VERSION == VERSION_DEMO
    nullptr,  // g_profile_KAMOME2 (d_a_kamome2 not built)
#endif
    nullptr,  // g_profile_NPC_KAM (d_a_npc_kamome not built)
    nullptr,  // g_profile_WBIRD (d_a_wbird not built)
    nullptr,  // g_profile_DEMO_KMM (d_a_demo_kmm not built)
    nullptr,  // g_profile_NZ (d_a_nz not built)
    nullptr,  // g_profile_NZG (d_a_nzg not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_KN),
    nullptr,  // g_profile_DEMO_DK (d_a_demo_dk not built)
    nullptr,  // g_profile_AM (d_a_am not built)
    nullptr,  // g_profile_AM2 (d_a_am2 not built)
    nullptr,  // g_profile_GM (d_a_gm not built)
    nullptr,  // g_profile_KS (d_a_ks not built)
    nullptr,  // g_profile_CC (d_a_cc not built)
    nullptr,  // g_profile_BL (d_a_bl not built)
    nullptr,  // g_profile_WZ (d_a_wz not built)
    nullptr,  // g_profile_PH (d_a_ph not built)
    nullptr,  // g_profile_PZ (d_a_pz not built)
    nullptr,  // g_profile_BPW (d_a_bpw not built)
    nullptr,  // g_profile_PW (d_a_pw not built)
    nullptr,  // g_profile_JBO (d_a_jbo not built)
    nullptr,  // g_profile_BO (d_a_bo not built)
    nullptr,  // g_profile_KI (d_a_ki not built)
    nullptr,  // g_profile_MT (d_a_mt not built)
    nullptr,  // g_profile_BWD (d_a_bwd not built)
    nullptr,  // g_profile_BWDS (d_a_bwds not built)
    nullptr,  // g_profile_BWDG (d_a_bwdg not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_KB),
    reinterpret_cast<process_profile_definition*>(&g_profile_ESA),
    nullptr,  // g_profile_DR (d_a_dr not built)
    nullptr,  // g_profile_DR2 (d_a_dr2 not built)
    nullptr,  // g_profile_RD (d_a_rd not built)
    nullptr,  // g_profile_DAIOCTA (d_a_daiocta not built)
    nullptr,  // g_profile_DAIOCTA_EYE (d_a_daiocta_eye not built)
    nullptr,  // g_profile_OQ (d_a_oq not built)
    nullptr,  // g_profile_GY (d_a_gy not built)
    nullptr,  // g_profile_GY_CTRL (d_a_gy_ctrl not built)
    nullptr,  // g_profile_GY_CTRLB (d_a_gy_ctrl not built)
    nullptr,  // g_profile_Hot_Floor (d_a_hot_floor not built)
    nullptr,  // g_profile_Beam (d_a_beam not built)
    nullptr,  // g_profile_Bemos (d_a_obj_bemos not built)
    nullptr,  // g_profile_BTD (d_a_btd not built)
    nullptr,  // g_profile_BMD (d_a_bmd not built)
    nullptr,  // g_profile_BMDHAND (d_a_bmdhand not built)
    nullptr,  // g_profile_BMDFOOT (d_a_bmdfoot not built)
    nullptr,  // g_profile_DK (d_a_dk not built)
    nullptr,  // g_profile_BDK (d_a_bdk not built)
    nullptr,  // g_profile_BDKOBJ (d_a_bdkobj not built)
    nullptr,  // g_profile_BST (d_a_bst not built)
    nullptr,  // g_profile_FGANON (d_a_fganon not built)
    nullptr,  // g_profile_FGMAHOU (d_a_fgmahou not built)
    nullptr,  // g_profile_BGN (d_a_bgn not built)
    nullptr,  // g_profile_BGN2 (d_a_bgn2 not built)
    nullptr,  // g_profile_BGN3 (d_a_bgn3 not built)
    nullptr,  // g_profile_GND (d_a_gnd not built)
    nullptr,  // g_profile_PT (d_a_pt not built)
    nullptr,  // g_profile_SWTDOOR (d_a_swtdoor not built)
    nullptr,  // g_profile_MOZO (d_a_mozo not built)
    nullptr,  // g_profile_KUI (d_a_kui not built)
    nullptr,  // g_profile_SS (d_a_ss not built)
    nullptr,  // g_profile_SSS (d_a_sss not built)
    nullptr,  // g_profile_SITEM (d_a_sitem not built)
    nullptr,  // g_profile_MACHINE (d_a_machine not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_ITEM),
    nullptr,  // g_profile_BOSSITEM (d_a_boss_item not built)
    nullptr,  // g_profile_Demo_Item (d_a_demo_item not built)
    nullptr,  // g_profile_RACEITEM (d_a_race_item not built)
    nullptr,  // g_profile_ShopItem (d_a_shop_item not built)
    nullptr,  // g_profile_DEKU_ITEM (d_a_deku_item not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_SPC_ITEM01),
    nullptr,  // g_profile_Obj_Paper (d_a_obj_paper not built)
    nullptr,  // g_profile_Obj_Demo_Barrel (d_a_obj_demo_barrel not built)
    nullptr,  // g_profile_Obj_Dmgroom (d_a_obj_dmgroom not built)
    nullptr,  // g_profile_Obj_Doguu (d_a_obj_doguu not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_Obj_Wood),
    nullptr,  // g_profile_Obj_Flame (d_a_obj_flame not built)
    nullptr,  // g_profile_Obj_Buoyrace (d_a_obj_buoyrace not built)
    nullptr,  // g_profile_Obj_Coming (d_a_obj_coming not built)
    nullptr,  // g_profile_Coming2 (d_a_coming2 not built)
    nullptr,  // g_profile_Coming3 (d_a_coming3 not built)
    nullptr,  // g_profile_Obj_Mmrr (d_a_obj_mmrr not built)
    nullptr,  // g_profile_Obj_Pbka (d_a_obj_pbka not built)
    nullptr,  // g_profile_Obj_Plant (d_a_obj_plant not built)
    nullptr,  // g_profile_Obj_Gtaki (d_a_obj_gtaki not built)
    nullptr,  // g_profile_Obj_Yboil (d_a_obj_Yboil not built)
    nullptr,  // g_profile_Obj_Rflw (d_a_obj_rflw not built)
    nullptr,  // g_profile_Obj_Table (d_a_obj_table not built)
    nullptr,  // g_profile_Obj_Tenmado (d_a_obj_tenmado not built)
    nullptr,  // g_profile_Obj_Cafelmp (d_a_obj_cafelmp not built)
    nullptr,  // g_profile_Obj_Apzl (d_a_obj_apzl not built)
    nullptr,  // g_profile_Obj_Adnno (d_a_obj_adnno not built)
    nullptr,  // g_profile_Obj_Auzu (d_a_obj_auzu not built)
    nullptr,  // g_profile_Obj_Gong (d_a_obj_gong not built)
    nullptr,  // g_profile_Obj_Barrier (d_a_obj_barrier not built)
    nullptr,  // g_profile_Obj_Firewall (d_a_obj_firewall not built)
    nullptr,  // g_profile_Obj_TnTrap (d_a_obj_tntrap not built)
    nullptr,  // g_profile_Obj_Monument (d_a_obj_monument not built)
    nullptr,  // g_profile_Obj_Tapestry (d_a_obj_tapestry not built)
    nullptr,  // g_profile_Obj_HSH (d_a_obj_hsehi1 not built)
    nullptr,  // g_profile_Goal_Flag (d_a_goal_flag not built)
    nullptr,  // g_profile_TBOX (d_a_tbox not built)
    nullptr,  // g_profile_SBOX (d_a_sbox not built)
    nullptr,  // g_profile_BOMB: not defined in the decomp yet
    reinterpret_cast<process_profile_definition*>(&g_profile_Bomb2),
    nullptr,  // g_profile_BOMB_FLOWER (d_a_bflower not built)
    nullptr,  // g_profile_ACORN_LEAF (d_a_acorn_leaf not built)
    nullptr,  // g_profile_SWC00 (d_a_swc00 not built)
    nullptr,  // g_profile_FAN (d_a_fan not built)
    nullptr,  // g_profile_DOOR10 (d_a_door10 not built)
    nullptr,  // g_profile_DOOR12 (d_a_door12 not built)
    nullptr,  // g_profile_ATDOOR (d_a_atdoor not built)
    nullptr,  // g_profile_MDOOR (d_a_mdoor not built)
    nullptr,  // g_profile_KDDOOR (d_a_kddoor not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_KNOB00),
    nullptr,  // g_profile_MTOGE (d_a_mtoge not built)
    nullptr,  // g_profile_ANDSW0 (d_a_andsw0 not built)
    nullptr,  // g_profile_ANDSW2 (d_a_andsw2 not built)
    nullptr,  // g_profile_DAI (d_a_dai not built)
    nullptr,  // g_profile_SW_ATTACK (d_a_swattack not built)
    nullptr,  // g_profile_SW_ITEM (d_a_switem not built)
    nullptr,  // g_profile_SW_TACT (d_a_swtact not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_NH),
    nullptr,  // g_profile_NPC_OS (d_a_npc_os not built)
    nullptr,  // g_profile_NPC_YM1 (d_a_npc_ym1 not built)
    nullptr,  // g_profile_NPC_YM2 (d_a_npc_ym1 not built)
    nullptr,  // g_profile_NPC_YW1 (d_a_npc_yw1 not built)
    nullptr,  // g_profile_NPC_JI1 (d_a_npc_ji1 not built)
    nullptr,  // g_profile_NPC_KO1 (d_a_npc_ko1 not built)
    nullptr,  // g_profile_NPC_KO2 (d_a_npc_ko1 not built)
    nullptr,  // g_profile_NPC_LS1 (d_a_npc_ls1 not built)
    nullptr,  // g_profile_NPC_P1 (d_a_npc_p1 not built)
    nullptr,  // g_profile_NPC_P2 (d_a_npc_p2 not built)
    nullptr,  // g_profile_NPC_SARACE (d_a_npc_sarace not built)
    nullptr,  // g_profile_NPC_TC (d_a_npc_tc not built)
    nullptr,  // g_profile_NPC_BM1 (d_a_npc_bm1 not built)
    nullptr,  // g_profile_NPC_BM2 (d_a_npc_bm1 not built)
    nullptr,  // g_profile_NPC_BM3 (d_a_npc_bm1 not built)
    nullptr,  // g_profile_NPC_BM4 (d_a_npc_bm1 not built)
    nullptr,  // g_profile_NPC_BM5 (d_a_npc_bm1 not built)
    nullptr,  // g_profile_NPC_OB1 (d_a_npc_ob1 not built)
    nullptr,  // g_profile_NPC_AJ1 (d_a_npc_aj1 not built)
    nullptr,  // g_profile_NPC_KM1 (d_a_npc_km1 not built)
    nullptr,  // g_profile_NPC_CB1 (d_a_npc_cb1 not built)
    nullptr,  // g_profile_NPC_BA1 (d_a_npc_ba1 not built)
    nullptr,  // g_profile_NPC_BJ1 (d_a_npc_bj1 not built)
    nullptr,  // g_profile_NPC_BJ2 (d_a_npc_bj1 not built)
    nullptr,  // g_profile_NPC_BJ3 (d_a_npc_bj1 not built)
    nullptr,  // g_profile_NPC_BJ4 (d_a_npc_bj1 not built)
    nullptr,  // g_profile_NPC_BJ5 (d_a_npc_bj1 not built)
    nullptr,  // g_profile_NPC_BJ6 (d_a_npc_bj1 not built)
    nullptr,  // g_profile_NPC_BJ7 (d_a_npc_bj1 not built)
    nullptr,  // g_profile_NPC_BJ8 (d_a_npc_bj1 not built)
    nullptr,  // g_profile_NPC_BJ9 (d_a_npc_bj1 not built)
    nullptr,  // g_profile_NPC_BS1 (d_a_npc_bs1 not built)
    nullptr,  // g_profile_NPC_BMCON1 (d_a_npc_bmcon1 not built)
    nullptr,  // g_profile_NPC_BMS1 (d_a_npc_bms1 not built)
    nullptr,  // g_profile_NPC_BMSW (d_a_npc_bmsw not built)
    nullptr,  // g_profile_NPC_BTSW (d_a_npc_btsw not built)
    nullptr,  // g_profile_NPC_BTSW2 (d_a_npc_btsw2 not built)
    nullptr,  // g_profile_NPC_DS1 (d_a_npc_ds1 not built)
    nullptr,  // g_profile_NPC_RSH1 (d_a_npc_rsh1 not built)
    nullptr,  // g_profile_NPC_KK1 (d_a_npc_kk1 not built)
    nullptr,  // g_profile_NPC_PM1 (d_a_npc_pm1 not built)
    nullptr,  // g_profile_NPC_KP1 (d_a_npc_kp1 not built)
    nullptr,  // g_profile_NPC_PF1 (d_a_npc_pf1 not built)
    nullptr,  // g_profile_NPC_GP1 (d_a_npc_gp1 not built)
    nullptr,  // g_profile_NPC_JB1 (d_a_npc_jb1 not built)
    nullptr,  // g_profile_NPC_KF1 (d_a_npc_kf1 not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_NPC_FA1),
    nullptr,  // g_profile_NPC_AUCTION (d_a_npc_auction not built)
    nullptr,  // g_profile_NPC_KG1 (d_a_npc_kg1 not built)
    nullptr,  // g_profile_NPC_KG2 (d_a_npc_kg2 not built)
    nullptr,  // g_profile_NPC_TT (d_a_npc_tt not built)
    nullptr,  // g_profile_NPC_HR (d_a_npc_hr not built)
    nullptr,  // g_profile_NPC_HO (d_a_npc_ho not built)
    nullptr,  // g_profile_NPC_MD (d_a_npc_md not built)
    nullptr,  // g_profile_NPC_UK (d_a_npc_uk not built)
    nullptr,  // g_profile_BIGELF (d_a_bigelf not built)
    nullptr,  // g_profile_NPC_CO1 (d_a_npc_co1 not built)
    nullptr,  // g_profile_NPC_ZK1 (d_a_npc_zk1 not built)
    nullptr,  // g_profile_NPC_ROTEN (d_a_npc_roten not built)
    nullptr,  // g_profile_NPC_PEOPLE (d_a_npc_people not built)
    nullptr,  // g_profile_NPC_GK1 (d_a_npc_gk1 not built)
    nullptr,  // g_profile_NPC_PHOTO (d_a_npc_photo not built)
    nullptr,  // g_profile_NPC_AC1 (d_a_npc_ac1 not built)
    nullptr,  // g_profile_NPC_HI1 (d_a_npc_hi1 not built)
    nullptr,  // g_profile_NPC_SV (d_a_npc_sv not built)
    nullptr,  // g_profile_NPC_MT (d_a_npc_mt not built)
    nullptr,  // g_profile_NPC_MN (d_a_npc_mn not built)
    nullptr,  // g_profile_NPC_AH (d_a_npc_ah not built)
    nullptr,  // g_profile_AUCTION (d_a_auction not built)
    nullptr,  // g_profile_KYTAG00 (d_a_kytag00 not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_KYTAG01),
    nullptr,  // g_profile_KYTAG02 (d_a_kytag02 not built)
    nullptr,  // g_profile_KYTAG03 (d_a_kytag03 not built)
    nullptr,  // g_profile_KYTAG04 (d_a_kytag04 not built)
    nullptr,  // g_profile_KYTAG05 (d_a_kytag05 not built)
    nullptr,  // g_profile_KYTAG06 (d_a_kytag06 not built)
    nullptr,  // g_profile_KYTAG07 (d_a_kytag07 not built)
    nullptr,  // g_profile_WindTag (d_a_wind_tag not built)
    nullptr,  // g_profile_YOUGAN (d_a_yougan not built)
    nullptr,  // g_profile_Mmusic (d_a_mmusic not built)
    nullptr,  // g_profile_Komore (d_a_komore not built)
    nullptr,  // g_profile_Tpota (d_a_tpota not built)
    nullptr,  // g_profile_Obj_Itnak (d_a_obj_Itnak not built)
    nullptr,  // g_profile_Obj_Zouk (d_a_obj_zouK not built)
    nullptr,  // g_profile_Ykgr (d_a_ykgr not built)
    nullptr,  // g_profile_SAKU (d_a_saku not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_Iball),
    reinterpret_cast<process_profile_definition*>(&g_profile_DISAPPEAR),
    nullptr,  // g_profile_Salvage (d_a_salvage not built)
    nullptr,  // g_profile_SALVAGE_TBOX (d_a_salvage_tbox not built)
    nullptr,  // g_profile_Kmon (d_a_kmon not built)
    nullptr,  // g_profile_OBJ_FIGURE (d_a_obj_figure not built)
    nullptr,  // g_profile_OBJ_HAT (d_a_obj_hat not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_DEMO00),
    reinterpret_cast<process_profile_definition*>(&g_profile_Lwood),
    nullptr,  // g_profile_Dummy (d_a_dummy not built)
    nullptr,  // g_profile_TAG_EVENT (d_a_tag_event not built)
    nullptr,  // g_profile_TAG_HINT (d_a_tag_hint not built)
    nullptr,  // g_profile_TAG_MSG (d_a_tag_msg not built)
    nullptr,  // g_profile_TAG_ETC (d_a_tag_etc not built)
    nullptr,  // g_profile_TAG_ISLAND (d_a_tag_island not built)
    nullptr,  // g_profile_TAG_KF1 (d_a_tag_kf1 not built)
    nullptr,  // g_profile_TAG_KK1 (d_a_tag_kk1 not built)
    nullptr,  // g_profile_TAG_PHOTO (d_a_tag_photo not built)
    nullptr,  // g_profile_TAG_KB_ITEM (d_a_tag_kb_item not built)
    nullptr,  // g_profile_TAG_MK (d_a_tag_mk not built)
    nullptr,  // g_profile_TAG_MDCB (d_a_tag_md_cb not built)
    nullptr,  // g_profile_TAG_BA1 (d_a_tag_ba1 not built)
    nullptr,  // g_profile_TagRock (d_a_fallrock_tag not built)
    nullptr,  // g_profile_FallRock (d_a_fallrock not built)
    nullptr,  // g_profile_SteamTag (d_a_steam_tag not built)
    nullptr,  // g_profile_Fire (d_a_fire not built)
    nullptr,  // g_profile_BRANCH (d_a_branch not built)
    nullptr,  // g_profile_NPC_ZL1 (d_a_npc_zl1 not built)
    nullptr,  // g_profile_WATERFALL (d_a_waterfall not built)
    nullptr,  // g_profile_LIGHTBRIDGE (d_a_lbridge not built)
    nullptr,  // g_profile_LIGHTSTAIR (d_a_lstair not built)
    nullptr,  // g_profile_WALL (d_a_wall not built)
    nullptr,  // g_profile_SW_PROPELLER (d_a_swpropeller not built)
    nullptr,  // g_profile_IKARI (d_a_ikari not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_BOOMERANG),
    reinterpret_cast<process_profile_definition*>(&g_profile_AGB),
    nullptr,  // g_profile_AGBSW0 (d_a_agbsw0 not built)
    nullptr,  // g_profile_MAGMA (d_a_magma not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_GRASS),
    reinterpret_cast<process_profile_definition*>(&g_profile_KY_THUNDER),
    reinterpret_cast<process_profile_definition*>(&g_profile_VRBOX),
    reinterpret_cast<process_profile_definition*>(&g_profile_VRBOX2),
    reinterpret_cast<process_profile_definition*>(&g_profile_BG),
    nullptr,  // g_profile_Obj_Tower (d_a_obj_tower not built)
    nullptr,  // g_profile_Obj_DoguuD (d_a_obj_doguu_demo not built)
    nullptr,  // g_profile_SPOTBOX (d_a_spotbox not built)
    nullptr,  // g_profile_TORNADO (d_a_tornado not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_TITLE),
    nullptr,  // g_profile_MP (d_a_movie_player not built)
    nullptr,  // g_profile_LODBG (d_a_lod_bg not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_HIMO2),
    nullptr,  // g_profile_HIMO3 (d_a_himo3 not built)
    nullptr,  // g_profile_ATT (d_a_att not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_WPILLAR),
    nullptr,  // g_profile_Hys (d_a_hys not built)
    nullptr,  // g_profile_SWHIT0 (d_a_swhit0 not built)
    nullptr,  // g_profile_TAG_GSHIP (d_a_tag_ghostship not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_TSUBO),
    nullptr,  // g_profile_STONE (d_a_stone not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_Stone2),
    nullptr,  // g_profile_Obj_Barrel (d_a_obj_barrel not built)
    nullptr,  // g_profile_Obj_Barrel2 (d_a_obj_barrel2 not built)
    nullptr,  // g_profile_Obj_Try (d_a_obj_try not built)
    nullptr,  // g_profile_Obj_Vtil (d_a_obj_vtil not built)
    nullptr,  // g_profile_Obj_Ice (d_a_obj_ice not built)
    nullptr,  // g_profile_Obj_Mshokki (d_a_obj_mshokki not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_STANDITEM),
    nullptr,  // g_profile_BOKO (d_a_boko not built)
    nullptr,  // g_profile_TAMA (d_a_tama not built)
    nullptr,  // g_profile_Obj_Buoyflag (d_a_obj_buoyflag not built)
    nullptr,  // g_profile_Obj_Correct (d_a_obj_correct not built)
    nullptr,  // g_profile_Obj_Eff (d_a_obj_eff not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_WATER_MARK),
    nullptr,  // g_profile_Tag_Light (d_a_tag_light not built)
    nullptr,  // g_profile_Tag_Attention (d_a_tag_attention not built)
    nullptr,  // g_profile_Tag_Waterlevel (d_a_tag_waterlevel not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_ARROW),
    nullptr,  // g_profile_ARROW_ICEEFF (d_a_arrow_iceeff not built)
    nullptr,  // g_profile_ARROW_LIGHTEFF (d_a_arrow_lighteff not built)
    nullptr,  // g_profile_Obj_Timer (d_a_obj_timer not built)
    reinterpret_cast<process_profile_definition*>(&g_profile_CAMERA),
    reinterpret_cast<process_profile_definition*>(&g_profile_CAMERA2),
    reinterpret_cast<process_profile_definition*>(&g_profile_KYEFF),
    reinterpret_cast<process_profile_definition*>(&g_profile_KYEFF2),
#if VERSION == VERSION_PAL
    reinterpret_cast<process_profile_definition*>(&g_profile_MSG3),
#endif
    reinterpret_cast<process_profile_definition*>(&g_profile_MESG),
    reinterpret_cast<process_profile_definition*>(&g_profile_MSG),
    reinterpret_cast<process_profile_definition*>(&g_profile_MSG2),
#if VERSION != VERSION_PAL
    reinterpret_cast<process_profile_definition*>(&g_profile_MSG3),
#endif
    reinterpret_cast<process_profile_definition*>(&g_profile_MENUWINDOW),
    reinterpret_cast<process_profile_definition*>(&g_profile_Menu_Cloth),
    reinterpret_cast<process_profile_definition*>(&g_profile_TIMER),
    reinterpret_cast<process_profile_definition*>(&g_profile_AUCTION_SCREEN),
    reinterpret_cast<process_profile_definition*>(&g_profile_PLACE_NAME),
    reinterpret_cast<process_profile_definition*>(&g_profile_MINIGAME_STARTER),
    reinterpret_cast<process_profile_definition*>(&g_profile_MINIGAME_TERMINATER),
    reinterpret_cast<process_profile_definition*>(&g_profile_METER),
    reinterpret_cast<process_profile_definition*>(&g_profile_OPERATE_WIND),
    reinterpret_cast<process_profile_definition*>(&g_profile_SCP),
    reinterpret_cast<process_profile_definition*>(&g_profile_PB),
    reinterpret_cast<process_profile_definition*>(&g_profile_GAMEOVER),
    nullptr,
};

// Profile names by process name, for --trace (src/dusk/trace.cpp).
extern const char* const g_fpcPfLst_ProfileNames[] = {
    "OVERLAP0",
    "OVERLAP1",
    "OVERLAP6",
    "OVERLAP7",
    "OVERLAP8",
    "LOGO_SCENE",
    "MENU_SCENE",
    "PLAY_SCENE",
    "OPENING_SCENE",
    "OPENING2_SCENE",
    "TITLE_SCENE",
    "ENDING_SCENE",
    "NAME_SCENE",
    "NAMEEX_SCENE",
    "OPEN_SCENE",
    "OPEN2_SCENE",
    "OVERLAP2",
    "OVERLAP3",
    "OVERLAP4",
    "OVERLAP5",
    "ROOM_SCENE",
    "KANKYO",
    "ALLDIE",
    "ENVSE",
    "WIND_ARROW",
    "WPOT_WATER",
    "LEVEL_SE",
    "THROWSTONE",
    "TAG_EVSW",
    "Obj_Swpush",
    "Obj_Swheavy",
    "Obj_Swflat",
    "Obj_Swlight",
    "Obj_Swhammer",
    "Obj_Quake",
    "Obj_Drift",
    "Tag_Volcano",
    "TAG_SO",
    "Obj_Pbco",
    "SEATAG",
    "SEA",
    "Obj_Tide",
    "Hmlif",
    "SCENECHG",
    "Obj_Magmarock",
    "Obj_Movebox",
    "Obj_Tribox",
    "Obj_Shelf",
    "Obj_Hlift",
    "Obj_Hami2",
    "Obj_Hami3",
    "Obj_Hami4",
    "Obj_Hbrf1",
    "Obj_Volcano",
    "Obj_Vmc",
    "Obj_Usovmc",
    "Obj_Vfan",
    "Obj_Iceisland",
    "Obj_Dragonhead",
    "Obj_Pirateship",
    "Obj_Tousekiki",
    "Tag_Ret",
    "Kaji",
    "Canon",
    "MGBOARD",
    "OBJ_CANON",
    "OBJ_OTBLE",
    "OBJ_WARPT",
    "OBJ_SEARCH",
    "OBJ_TORIPOST",
    "OBJ_IKADA",
    "OBJ_MJDOOR",
    "OBJ_PFALL",
    "OBJ_HOLE",
    "Obj_Stair",
    "Obj_Lpalm",
    "Obj_Mtest",
    "Obj_Mkie",
    "Obj_Mkiek",
    "Obj_MknjD",
    "Obj_Msdan",
    "Obj_MsdanSub",
    "Obj_Msdan2",
    "Obj_MsdanSub2",
    "Obj_Nest",
    "Obj_Ojtree",
    "Obj_Ospbox",
    "Obj_Ladder",
    "Obj_Smplbg",
    "Obj_Akabe",
    "Obj_Ashut",
    "BRIDGE",
    "MSW",
    "MFLFT",
    "KLFT",
    "ICE_LIFT",
    "AMI_PROP",
    "PEDESTAL",
    "FLOOR",
    "KITA",
    "KOKIIE",
    "SHAND",
    "BITA",
    "SK",
    "SK2",
    "SSK",
    "WARPFLOWER",
    "WARPFOUT",
    "WARPLIGHT",
    "WARPHYRULE",
    "WARPDEMO20",
    "WARPGANON",
    "WARPMAJYUU",
    "Balancelift",
    "SHUTTER",
    "SHUTTER2",
    "WINDMILL",
    "MBDOOR",
    "NPC_DE1",
    "NPC_NZ",
    "NPC_SO",
    "FM",
    "LEAF_LIFT",
    "Obj_Roten",
    "TOGE",
    "Obj_Ferris",
    "Obj_Xfuta",
    "Obj_Gaship",
    "Obj_Rforce",
    "Obj_Gaship2",
    "Obj_Light",
    "Obj_Homen",
    "Obj_Homensmk",
    "Obj_Ftree",
    "Obj_Vds",
    "Obj_Vyasi",
    "Obj_Ajav",
    "Obj_Trap",
    "Obj_Hha",
    "Obj_Htetu1",
    "Obj_Gnntakis",
    "Obj_Gnntakie",
    "Obj_Gnnbtaki",
    "Obj_Rcloud",
    "Obj_Gryw00",
    "Obj_AjavW",
    "Obj_Leaves",
    "Obj_YLzou",
    "Obj_Gbed",
    "Obj_Vteng",
    "Obj_Hfuck1",
    "Obj_Ohatch",
    "Obj_Hcbh",
    "Obj_Ygush00",
    "Obj_Bscurtain",
    "Obj_Shmrgrd",
    "Obj_Eayogn",
    "Obj_Vmsms",
    "Obj_Vmsdz",
    "Ygcwp",
    "Obj_Vgnfd",
    "Obj_Kanoke",
    "Obj_Eskban",
    "Obj_Ekskz",
    "Obj_Ebomzo",
    "Obj_Kanat",
    "Obj_Aygr",
    "SHIP",
    "Obj_Jump",
    "PLAYER",
    "HOOKSHOT",
    "NPC_MK",
    "GRID",
    "SAIL",
    "PIRATE_FLAG",
    "MAJUU_FLAG",
    "Tori_Flag",
    "Sie_Flag",
    "SYAN",
    "AYUSH",
    "OSHIP",
    "RECTANGLE",
    "BB",
    "KANBAN",
    "HITOBJ",
    "KT",
    "EP",
    "LAMP",
    "FF",
    "MO2",
    "BK",
    "ST",
    "TN",
    "MANT",
    "KANTERA",
    "KAMOME",
#if VERSION == VERSION_DEMO
    "KAMOME2",
#endif
    "NPC_KAM",
    "WBIRD",
    "DEMO_KMM",
    "NZ",
    "NZG",
    "KN",
    "DEMO_DK",
    "AM",
    "AM2",
    "GM",
    "KS",
    "CC",
    "BL",
    "WZ",
    "PH",
    "PZ",
    "BPW",
    "PW",
    "JBO",
    "BO",
    "KI",
    "MT",
    "BWD",
    "BWDS",
    "BWDG",
    "KB",
    "ESA",
    "DR",
    "DR2",
    "RD",
    "DAIOCTA",
    "DAIOCTA_EYE",
    "OQ",
    "GY",
    "GY_CTRL",
    "GY_CTRLB",
    "Hot_Floor",
    "Beam",
    "Bemos",
    "BTD",
    "BMD",
    "BMDHAND",
    "BMDFOOT",
    "DK",
    "BDK",
    "BDKOBJ",
    "BST",
    "FGANON",
    "FGMAHOU",
    "BGN",
    "BGN2",
    "BGN3",
    "GND",
    "PT",
    "SWTDOOR",
    "MOZO",
    "KUI",
    "SS",
    "SSS",
    "SITEM",
    "MACHINE",
    "ITEM",
    "BOSSITEM",
    "Demo_Item",
    "RACEITEM",
    "ShopItem",
    "DEKU_ITEM",
    "SPC_ITEM01",
    "Obj_Paper",
    "Obj_Demo_Barrel",
    "Obj_Dmgroom",
    "Obj_Doguu",
    "Obj_Wood",
    "Obj_Flame",
    "Obj_Buoyrace",
    "Obj_Coming",
    "Coming2",
    "Coming3",
    "Obj_Mmrr",
    "Obj_Pbka",
    "Obj_Plant",
    "Obj_Gtaki",
    "Obj_Yboil",
    "Obj_Rflw",
    "Obj_Table",
    "Obj_Tenmado",
    "Obj_Cafelmp",
    "Obj_Apzl",
    "Obj_Adnno",
    "Obj_Auzu",
    "Obj_Gong",
    "Obj_Barrier",
    "Obj_Firewall",
    "Obj_TnTrap",
    "Obj_Monument",
    "Obj_Tapestry",
    "Obj_HSH",
    "Goal_Flag",
    "TBOX",
    "SBOX",
    "BOMB",
    "Bomb2",
    "BOMB_FLOWER",
    "ACORN_LEAF",
    "SWC00",
    "FAN",
    "DOOR10",
    "DOOR12",
    "ATDOOR",
    "MDOOR",
    "KDDOOR",
    "KNOB00",
    "MTOGE",
    "ANDSW0",
    "ANDSW2",
    "DAI",
    "SW_ATTACK",
    "SW_ITEM",
    "SW_TACT",
    "NH",
    "NPC_OS",
    "NPC_YM1",
    "NPC_YM2",
    "NPC_YW1",
    "NPC_JI1",
    "NPC_KO1",
    "NPC_KO2",
    "NPC_LS1",
    "NPC_P1",
    "NPC_P2",
    "NPC_SARACE",
    "NPC_TC",
    "NPC_BM1",
    "NPC_BM2",
    "NPC_BM3",
    "NPC_BM4",
    "NPC_BM5",
    "NPC_OB1",
    "NPC_AJ1",
    "NPC_KM1",
    "NPC_CB1",
    "NPC_BA1",
    "NPC_BJ1",
    "NPC_BJ2",
    "NPC_BJ3",
    "NPC_BJ4",
    "NPC_BJ5",
    "NPC_BJ6",
    "NPC_BJ7",
    "NPC_BJ8",
    "NPC_BJ9",
    "NPC_BS1",
    "NPC_BMCON1",
    "NPC_BMS1",
    "NPC_BMSW",
    "NPC_BTSW",
    "NPC_BTSW2",
    "NPC_DS1",
    "NPC_RSH1",
    "NPC_KK1",
    "NPC_PM1",
    "NPC_KP1",
    "NPC_PF1",
    "NPC_GP1",
    "NPC_JB1",
    "NPC_KF1",
    "NPC_FA1",
    "NPC_AUCTION",
    "NPC_KG1",
    "NPC_KG2",
    "NPC_TT",
    "NPC_HR",
    "NPC_HO",
    "NPC_MD",
    "NPC_UK",
    "BIGELF",
    "NPC_CO1",
    "NPC_ZK1",
    "NPC_ROTEN",
    "NPC_PEOPLE",
    "NPC_GK1",
    "NPC_PHOTO",
    "NPC_AC1",
    "NPC_HI1",
    "NPC_SV",
    "NPC_MT",
    "NPC_MN",
    "NPC_AH",
    "AUCTION",
    "KYTAG00",
    "KYTAG01",
    "KYTAG02",
    "KYTAG03",
    "KYTAG04",
    "KYTAG05",
    "KYTAG06",
    "KYTAG07",
    "WindTag",
    "YOUGAN",
    "Mmusic",
    "Komore",
    "Tpota",
    "Obj_Itnak",
    "Obj_Zouk",
    "Ykgr",
    "SAKU",
    "Iball",
    "DISAPPEAR",
    "Salvage",
    "SALVAGE_TBOX",
    "Kmon",
    "OBJ_FIGURE",
    "OBJ_HAT",
    "DEMO00",
    "Lwood",
    "Dummy",
    "TAG_EVENT",
    "TAG_HINT",
    "TAG_MSG",
    "TAG_ETC",
    "TAG_ISLAND",
    "TAG_KF1",
    "TAG_KK1",
    "TAG_PHOTO",
    "TAG_KB_ITEM",
    "TAG_MK",
    "TAG_MDCB",
    "TAG_BA1",
    "TagRock",
    "FallRock",
    "SteamTag",
    "Fire",
    "BRANCH",
    "NPC_ZL1",
    "WATERFALL",
    "LIGHTBRIDGE",
    "LIGHTSTAIR",
    "WALL",
    "SW_PROPELLER",
    "IKARI",
    "BOOMERANG",
    "AGB",
    "AGBSW0",
    "MAGMA",
    "GRASS",
    "KY_THUNDER",
    "VRBOX",
    "VRBOX2",
    "BG",
    "Obj_Tower",
    "Obj_DoguuD",
    "SPOTBOX",
    "TORNADO",
    "TITLE",
    "MP",
    "LODBG",
    "HIMO2",
    "HIMO3",
    "ATT",
    "WPILLAR",
    "Hys",
    "SWHIT0",
    "TAG_GSHIP",
    "TSUBO",
    "STONE",
    "Stone2",
    "Obj_Barrel",
    "Obj_Barrel2",
    "Obj_Try",
    "Obj_Vtil",
    "Obj_Ice",
    "Obj_Mshokki",
    "STANDITEM",
    "BOKO",
    "TAMA",
    "Obj_Buoyflag",
    "Obj_Correct",
    "Obj_Eff",
    "WATER_MARK",
    "Tag_Light",
    "Tag_Attention",
    "Tag_Waterlevel",
    "ARROW",
    "ARROW_ICEEFF",
    "ARROW_LIGHTEFF",
    "Obj_Timer",
    "CAMERA",
    "CAMERA2",
    "KYEFF",
    "KYEFF2",
#if VERSION == VERSION_PAL
    "MSG3",
#endif
    "MESG",
    "MSG",
    "MSG2",
#if VERSION != VERSION_PAL
    "MSG3",
#endif
    "MENUWINDOW",
    "Menu_Cloth",
    "TIMER",
    "AUCTION_SCREEN",
    "PLACE_NAME",
    "MINIGAME_STARTER",
    "MINIGAME_TERMINATER",
    "METER",
    "OPERATE_WIND",
    "SCP",
    "PB",
    "GAMEOVER",
    "",
};
extern const int g_fpcPfLst_ProfileNum = sizeof(g_fpcPfLst_ProfileNames) / sizeof(g_fpcPfLst_ProfileNames[0]);
