#!/usr/bin/env python3
"""Generate src/dusk/ww_profile_list.cpp: the process profile list for the PC build.

The decomp's src/f_pc/f_pc_profile_lst.cpp declares every profile as process_profile_definition,
but each one is defined with its own type (actor_process_profile_definition, ...). MWCC did not
mind; MSVC encodes a variable's type in its link name, so those declarations never resolve. This
writes the same list, in the same order and with the same #if lines, declaring each profile with
the type it is defined with. Profiles whose actor REL is not built (see WW_ENABLED_RELS in
files.cmake) are nullptr, so the game can come up one scene at a time.

Re-run after changing WW_ENABLED_RELS or importing a new decomp revision:

    python tools/gen_profile_list.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIST = ROOT / "src" / "f_pc" / "f_pc_profile_lst.cpp"
OUT = ROOT / "src" / "dusk" / "ww_profile_list.cpp"
DEF = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s+(g_profile_[A-Za-z0-9_]+)\s*=", re.M)


def cmake_list(text: str, name: str) -> list[str]:
    m = re.search(r"set\(" + name + r"\s*\n(.*?)\n\)", text, re.S)
    return m.group(1).split() if m else []


def main() -> int:
    files_cmake = (ROOT / "files.cmake").read_text(encoding="utf-8")
    ww_files = (ROOT / "cmake" / "WWGameFiles.cmake").read_text(encoding="utf-8")
    enabled_rels = cmake_list(files_cmake, "WW_ENABLED_RELS")
    built = set(cmake_list(ww_files, "WW_DOL_FILES"))
    built |= {f"src/d/actor/{rel}.cpp" for rel in enabled_rels}

    # profile name -> (type, defining file)
    defs = {}
    for path in (ROOT / "src").rglob("*.cpp"):
        rel = path.relative_to(ROOT).as_posix()
        if rel.startswith("src/dusk/"):
            continue
        for m in DEF.finditer(path.read_text(encoding="utf-8", errors="replace")):
            defs.setdefault(m.group(2), (m.group(1), rel))

    text = LIST.read_text(encoding="utf-8")
    body = re.search(r"g_fpcPfLst_ProfileList\[\] = \{\n(.*?)\n\};", text, re.S).group(1)
    entries, externs, used, missing = [], [], 0, []
    for line in body.splitlines():
        stripped = line.strip()
        m = re.fullmatch(r"&(g_profile_\w+),", stripped)
        if m:
            name = m.group(1)
            if name not in defs:
                missing.append(name)
                entries.append(f"    nullptr,  // {name}: not defined in the decomp yet")
                continue
            type_, path = defs[name]
            if path in built:
                externs.append(f"extern {type_} {name};")
                entries.append(f"    reinterpret_cast<process_profile_definition*>(&{name}),")
                used += 1
            else:
                entries.append(f"    nullptr,  // {name} ({Path(path).stem} not built)")
        elif stripped in ("NULL,", "nullptr,"):
            entries.append("    nullptr,")
        elif stripped.startswith("#") or not stripped:
            entries.append(stripped)
        else:
            print(f"error: unexpected profile list line: {line!r}", file=sys.stderr)
            return 1

    out = [
        "// Generated by tools/gen_profile_list.py from src/f_pc/f_pc_profile_lst.cpp. Do not edit.",
        "// The process profile list, indexed by process name. Profiles of actors that are not built",
        "// (WW_ENABLED_RELS in files.cmake) are nullptr.",
        "",
        '#include "f_pc/f_pc_profile.h"',
        '#include "f_op/f_op_actor.h"',
        '#include "f_op/f_op_camera.h"',
        '#include "f_op/f_op_kankyo.h"',
        '#include "f_op/f_op_msg_mng.h"',
        '#include "f_op/f_op_overlap_mng.h"',
        '#include "f_op/f_op_scene.h"',
        "",
        *sorted(set(externs)),
        "",
        "process_profile_definition* g_fpcPfLst_ProfileList[] = {",
        *entries,
        "};",
        "",
    ]
    OUT.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {used} profiles linked, "
          f"{sum(1 for e in entries if 'not built' in e)} not built")
    if missing:
        print(f"note: not defined in the decomp yet: {', '.join(missing)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
