#!/usr/bin/env python3
"""Generate cmake/WWGameFiles.cmake from the decomp's upstream/tww/configure.py.

Only the `config.libs = [...]` list is evaluated (via ast), with stand-ins for its helper
functions, so none of configure.py's build logic runs. Re-run after every TWW import:

    python tools/gen_ww_files.py
"""

import ast
import sys
import types
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIGURE = ROOT / "upstream" / "tww" / "configure.py"
OUTPUT = ROOT / "cmake" / "WWGameFiles.cmake"

# Libraries that make up the game DOL (besides SSystem and JSystem).
DOL_LIBS = ["machine", "c", "framework", "dolzel", "DynamicLink"]
# Audio stack: replaced by a null implementation until audio is ported.
AUDIO_LIBS = ["JAudio", "JAZelAudio", "JStudio_JAudio"]
# Provided by aurora (Dolphin SDK), or PowerPC runtime/debugger/REL glue with no PC meaning.
SKIPPED_LIBS = ["gf", "exi", "Runtime.PPCEABI.H", "MSL_C", "TRK_MINNOW_DOLPHIN", "amcstubs",
                "OdemuExi2", "odenotstub", "REL"]


def load_libs() -> list[dict]:
    tree = ast.parse(CONFIGURE.read_text(encoding="utf-8"))
    node = next(n for n in tree.body
                if isinstance(n, ast.Assign) and ast.unparse(n.targets[0]) == "config.libs")

    class Names(dict):
        def __missing__(self, key):
            return f"<{key}>"  # cflags_* and status constants; only their presence matters

    def obj(status, path, **kwargs):
        return {"path": kwargs.get("source", path)}

    def lib(kind):
        return lambda name, objects, *args, **kwargs: {"lib": name, "kind": kind, "objects": objects}

    def actor_rel(status, name, extra_cflags=()):
        return {"lib": name, "kind": "actor", "objects": [obj(status, f"d/actor/{name}.cpp")]}

    names = Names(Object=obj, JSystemLib=lib("jsystem"), DolphinLib=lib("dolphin"), Rel=lib("rel"),
                  ActorRel=actor_rel, MatchingFor=lambda *v: None, EquivalentFor=lambda *v: None,
                  config=types.SimpleNamespace())
    exec(compile(ast.Module([node], []), str(CONFIGURE), "exec"), {}, names)
    return names["config"].libs


def cmake_list(name: str, paths: list[str]) -> str:
    body = "".join(f"        src/{p}\n" for p in paths)
    return f"set({name}\n{body})\n"


def main() -> int:
    libs = load_libs()
    by_name = {l["lib"]: l for l in libs}
    files = lambda names: [o["path"] for n in names for o in by_name[n]["objects"]]

    jsystem = [l for l in libs if l.get("kind") == "jsystem" and l["lib"] not in AUDIO_LIBS]
    actors = [l for l in libs if l.get("kind") == "actor"]
    rels = [l for l in libs if l.get("kind") == "rel"]

    known = set(DOL_LIBS + AUDIO_LIBS + SKIPPED_LIBS + ["SSystem"]) | {l["lib"] for l in jsystem + actors + rels}
    unknown = [l["lib"] for l in libs if l["lib"] not in known and l.get("kind") != "dolphin"]
    if unknown:
        print(f"error: unclassified libraries in configure.py: {', '.join(unknown)}", file=sys.stderr)
        return 1

    out = ["# Generated by tools/gen_ww_files.py from upstream/tww/configure.py. Do not edit.\n"]
    out.append(cmake_list("WW_DOL_FILES", files(DOL_LIBS)))
    out.append(cmake_list("WW_SSYSTEM_FILES", files(["SSystem"])))
    out.append(cmake_list("WW_AUDIO_FILES", files(AUDIO_LIBS)))
    out.append("set(WW_JSYSTEM_LIBS " + " ".join(l["lib"] for l in jsystem) + ")\n")
    for l in jsystem:
        out.append(cmake_list(f"WW_JSYSTEM_{l['lib']}_FILES", [o["path"] for o in l["objects"]]))
    out.append(cmake_list("WW_PROFILE_LIST_FILES", [o["path"] for l in rels for o in l["objects"]]))
    out.append("# Actor RELs, by REL name; each is d/actor/<name>.cpp.\n")
    out.append("set(WW_ACTOR_RELS\n" + "".join(f"        {l['lib']}\n" for l in actors) + ")\n")

    OUTPUT.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(files(DOL_LIBS))} DOL, {len(jsystem)} JSystem libs, "
          f"{len(actors)} actors")
    return 0


if __name__ == "__main__":
    sys.exit(main())
