#!/usr/bin/env python3
"""Generate src/dusk/ww_audio_null.cpp: no-op definitions for the game's audio API.

Audio (JAudio, JAZelAudio) is not ported yet, so its sources are not built. The game still calls
into it everywhere; this defines each audio function the linker asks for, doing nothing, with a
few explicit return values (OVERRIDES) where the game waits on audio being ready.

The symbol list lives in src/dusk/ww_audio_null.symbols (one MSVC-demangled signature per line).
Pass a link log to add the audio symbols it reports as unresolved, then the .cpp is rewritten:

    python tools/gen_audio_null.py [build.log]
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SYMBOLS = ROOT / "src" / "dusk" / "ww_audio_null.symbols"
OUT = ROOT / "src" / "dusk" / "ww_audio_null.cpp"
AUDIO = re.compile(r"\b(JAI\w*|JAS\w*|JASystem|JAInter|JAZel\w*|JStudio_JAudio)::")

# Bodies that differ from "do nothing, return zero". The wave-load checks the scenes wait on
# (checkFirstWaves, check1stDynamicWave, checkAllWaveLoadStatus) mean "still loading" when
# non-zero, so the default already reports audio as ready.
OVERRIDES = {
    "JAIZelBasic::JAIZelBasic": "zel_basic = this;",
}

HEADERS = [
    "JAZelAudio/JAIZelBasic.h",
    "JAZelAudio/JAIZelInst.h",
    "JAZelAudio/JAIZelAnime.h",
    "JSystem/JAudio/JAIAnimation.h",
    "JSystem/JAudio/JAIBankWave.h",
    "JSystem/JAudio/JAIBasic.h",
    "JSystem/JAudio/JAIGlobalParameter.h",
    "JSystem/JAudio/JAISequenceMgr.h",
    "JSystem/JAudio/JAISound.h",
    "JSystem/JAudio/JAIStreamMgr.h",
    "JSystem/JAudio/JASDvdThread.h",
    "JSystem/JStudio/JStudio_JAudio/control.h",
]


def unresolved(log: str) -> set[str]:
    found = set()
    for m in re.finditer(r'unresolved external symbol (?:"(.+?)" \(\S+\)|(\S+))', log):
        name = m.group(1) or m.group(2)
        if AUDIO.search(name):
            found.add(name)
    return found


def definition(sig: str) -> str:
    s = re.sub(r"^(public|protected|private): ", "", sig)
    s = re.sub(r"\b(virtual|static) ", "", s)
    s = s.replace("__cdecl ", "").replace("(__cdecl*)", "(*)")
    if "(" not in s:  # static data member, e.g. "class JAIZelBasic * JAIZelBasic::zel_basic"
        return f"{s};"
    head, args = s.split("(", 1)
    args = "(" + args
    parts = head.rsplit(" ", 1)
    ret, name = (parts[0], parts[1]) if len(parts) == 2 else ("", parts[0])
    qual = name.split("(")[0]
    if qual in OVERRIDES:
        body = OVERRIDES[qual]
    elif ret in ("", "void"):
        body = ""
    else:
        body = "return {};"
    if args == "(void)":
        args = "()"
    return f"{ret + ' ' if ret else ''}{name}{args} {{ {body} }}".replace("{  }", "{}")


def main() -> int:
    symbols = set(SYMBOLS.read_text(encoding="utf-8").splitlines()) if SYMBOLS.exists() else set()
    symbols.discard("")
    added = 0
    for log in sys.argv[1:]:
        new = unresolved(Path(log).read_text(encoding="utf-8", errors="replace")) - symbols
        symbols |= new
        added += len(new)
    SYMBOLS.write_text("\n".join(sorted(symbols)) + "\n", encoding="utf-8", newline="\n")

    out = [
        "// Generated by tools/gen_audio_null.py from ww_audio_null.symbols. Do not edit.",
        "// No-op audio until JAudio/JAZelAudio are ported: each function the game links against does",
        "// nothing, except where the game waits on audio being ready.",
        "",
        *[f'#include "{h}"' for h in HEADERS],
        "",
        *[definition(s) for s in sorted(symbols)],
        "",
    ]
    OUT.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"{len(symbols)} audio symbols ({added} new) -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
